-- ============================================================================
-- BLOCK 5 — CATALOG EXPERIENCE, CERTIFICATION & SCORECARD VALIDATION
-- Avidia Bank Take-Home Assessment
--
-- Suggested repo path:
--   evidence/block5/00_block5_validation.sql
-- ============================================================================

USE ROLE DATA_OWNER;
USE WAREHOUSE TRANSFORM_WH;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

-- 1. STREAMLIT OBJECT EXISTS
-- Screenshot: 01_streamlit_object.png
SHOW STREAMLITS IN SCHEMA GOVERNANCE.CATALOG;

-- 2. CATALOG ENTRY FOR MART_DEPOSITS
-- Screenshot: 02_catalog_master_mart_deposits.png
SELECT
    DATABASE_NAME,
    SCHEMA_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    DESCRIPTION,
    CDE_FLAG,
    CRITICALITY_LEVEL,
    DATA_OWNER,
    DATA_STEWARD,
    CERTIFICATION,
    LATEST_DQ_STATUS,
    LATEST_DQ_RUN,
    LAST_METADATA_REFRESH
FROM GOVERNANCE.CATALOG.CATALOG_MASTER_VIEW
WHERE DATABASE_NAME = 'ANALYTICS'
  AND SCHEMA_NAME = 'MARTS'
  AND TABLE_NAME = 'MART_DEPOSITS'
ORDER BY ORDINAL_POSITION;

-- 3. OWNERSHIP / STEWARDSHIP EVIDENCE USED BY CERTIFICATION
-- Screenshot: 03_certification_ownership_evidence.png
SELECT
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    EVIDENCE_TYPE,
    EVIDENCE_KEY,
    EVIDENCE_VALUE,
    CAPTURED_AT
FROM GOVERNANCE.CATALOG.CERTIFICATION_EVIDENCE
WHERE DATABASE_NAME = 'ANALYTICS'
  AND SCHEMA_NAME = 'MARTS'
  AND OBJECT_NAME = 'MART_DEPOSITS'
ORDER BY EVIDENCE_TYPE, EVIDENCE_KEY;

-- 4. ADOPTION / USAGE EVIDENCE
-- Screenshot: 04_adoption_evidence.png
SELECT
    ROLE_NAME,
    COUNT(*) AS QUERY_COUNT,
    MAX(QUERY_START_TIME) AS LAST_QUERY_TIME
FROM GOVERNANCE.CATALOG.ADOPTION_EVIDENCE
WHERE DATABASE_NAME = 'ANALYTICS'
  AND SCHEMA_NAME = 'MARTS'
  AND OBJECT_NAME = 'MART_DEPOSITS'
GROUP BY ROLE_NAME
ORDER BY ROLE_NAME;

SELECT
    QUERY_ID,
    ROLE_NAME,
    QUERY_START_TIME,
    QUERY_TEXT,
    CAPTURED_AT
FROM GOVERNANCE.CATALOG.ADOPTION_EVIDENCE
WHERE DATABASE_NAME = 'ANALYTICS'
  AND SCHEMA_NAME = 'MARTS'
  AND OBJECT_NAME = 'MART_DEPOSITS'
ORDER BY QUERY_START_TIME DESC
LIMIT 25;

-- 5. LATEST CERTIFICATION RUN
-- Screenshot: 05_latest_certification_run.png
SELECT
    CERTIFICATION_RUN_ID,
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    FINAL_STATUS,
    PASSED_CONTROLS,
    TOTAL_CONTROLS,
    CERTIFIED_BY,
    STARTED_AT,
    COMPLETED_AT
FROM GOVERNANCE.CATALOG.CERTIFICATION_RUN
WHERE DATABASE_NAME = 'ANALYTICS'
  AND SCHEMA_NAME = 'MARTS'
  AND OBJECT_NAME = 'MART_DEPOSITS'
ORDER BY COMPLETED_AT DESC;

-- 6. SEVEN-WORD SCORECARD
-- Screenshot: 06_seven_word_scorecard.png
SELECT
    CONTROL_NAME,
    CONTROL_STATUS,
    EVIDENCE_VALUE,
    EVIDENCE_DETAILS,
    EVALUATED_AT
FROM GOVERNANCE.CATALOG.CERTIFICATION_SCORECARD_CURRENT;

-- Compact 7/7 proof
SELECT
    COUNT(*) AS TOTAL_CONTROLS,
    COUNT_IF(CONTROL_STATUS = 'PASS') AS PASSED_CONTROLS,
    IFF(
        COUNT(*) = 7
        AND COUNT_IF(CONTROL_STATUS = 'PASS') = 7,
        '7/7',
        'NOT_7/7'
    ) AS SCORE
FROM GOVERNANCE.CATALOG.CERTIFICATION_SCORECARD_CURRENT;

-- 7. LIVE CERTIFICATION TAGS ON MART_DEPOSITS
-- Screenshot: 07_certification_tags.png
SELECT
    TAG_NAME,
    TAG_VALUE,
    APPLY_METHOD
FROM TABLE(
    ANALYTICS.INFORMATION_SCHEMA.TAG_REFERENCES(
        'ANALYTICS.MARTS.MART_DEPOSITS',
        'TABLE'
    )
)
WHERE UPPER(TAG_DATABASE) = 'GOVERNANCE'
  AND UPPER(TAG_SCHEMA) = 'CATALOG'
  AND UPPER(TAG_NAME) IN (
      'DATA_OWNER',
      'DATA_STEWARD',
      'CERTIFICATION',
      'LAST_CERTIFIED'
  )
ORDER BY TAG_NAME;

-- 8. CERTIFICATION RUN HISTORY
-- Screenshot: 08_certification_history.png
-- Assessment expects one successful certification and one refusal.
SELECT
    FINAL_STATUS,
    COUNT(*) AS RUN_COUNT,
    MAX(COMPLETED_AT) AS LATEST_RUN
FROM GOVERNANCE.CATALOG.CERTIFICATION_RUN
WHERE DATABASE_NAME = 'ANALYTICS'
  AND SCHEMA_NAME = 'MARTS'
  AND OBJECT_NAME = 'MART_DEPOSITS'
GROUP BY FINAL_STATUS
ORDER BY FINAL_STATUS;

-- 9. PROCEDURE EXISTS
SHOW PROCEDURES LIKE 'CERTIFY_MART_DEPOSITS'
IN SCHEMA GOVERNANCE.CATALOG;

-- 10. STREAMLIT VISUAL EVIDENCE
-- Screenshot: 09_streamlit_catalog.png
-- Open GOVERNANCE.CATALOG.AVIDIA_DATA_CATALOG and capture MART_DEPOSITS
-- showing owner/steward, certification, CDE, description, DQ, lineage,
-- usage/adoption and scorecard where visible.

-- 11. REFUSAL CHECK
-- If certification history contains only CERTIFIED, do not corrupt MART_DEPOSITS.
-- Create a controlled disposable/clone test object and prove certification
-- refuses when required evidence is missing. Implement separately only if needed.

-- ============================================================================
-- END BLOCK 5
-- ============================================================================
