-- metadata/apply_tags.sql
-- Apply tags to tables and columns (fully qualified, no USE statements)

USE ROLE DATA_OWNER;

-- Don't set database context - use fully qualified names for everything

-- ============================================
-- TAG RAW.PUBLIC TABLES
-- ============================================

ALTER TABLE RAW.PUBLIC.CUSTOMER
  SET TAG GOVERNANCE.CATALOG.LAYER = 'RAW',
      GOVERNANCE.CATALOG.DOMAIN = 'CUSTOMER',
      GOVERNANCE.CATALOG.SOURCE_SYSTEM = 'DATA_GENERATOR',
      GOVERNANCE.CATALOG.CERTIFICATION = 'IN_PROGRESS',
      GOVERNANCE.CATALOG.DATA_OWNER = 'Banking Operations';

ALTER TABLE RAW.PUBLIC.ACCOUNT
  SET TAG GOVERNANCE.CATALOG.LAYER = 'RAW',
      GOVERNANCE.CATALOG.DOMAIN = 'DEPOSIT',
      GOVERNANCE.CATALOG.SOURCE_SYSTEM = 'DATA_GENERATOR',
      GOVERNANCE.CATALOG.CERTIFICATION = 'IN_PROGRESS',
      GOVERNANCE.CATALOG.DATA_OWNER = 'Deposits Team';

ALTER TABLE RAW.PUBLIC.TRANSACTION
  SET TAG GOVERNANCE.CATALOG.LAYER = 'RAW',
      GOVERNANCE.CATALOG.DOMAIN = 'DEPOSIT',
      GOVERNANCE.CATALOG.SOURCE_SYSTEM = 'DATA_GENERATOR',
      GOVERNANCE.CATALOG.CERTIFICATION = 'IN_PROGRESS',
      GOVERNANCE.CATALOG.DATA_OWNER = 'Deposits Team';

ALTER TABLE RAW.PUBLIC.LOAN
  SET TAG GOVERNANCE.CATALOG.LAYER = 'RAW',
      GOVERNANCE.CATALOG.DOMAIN = 'LOAN',
      GOVERNANCE.CATALOG.SOURCE_SYSTEM = 'DATA_GENERATOR',
      GOVERNANCE.CATALOG.CERTIFICATION = 'IN_PROGRESS',
      GOVERNANCE.CATALOG.DATA_OWNER = 'Lending Team';

ALTER TABLE RAW.PUBLIC.GL_CONTROL
  SET TAG GOVERNANCE.CATALOG.LAYER = 'RAW',
      GOVERNANCE.CATALOG.DOMAIN = 'GL',
      GOVERNANCE.CATALOG.SOURCE_SYSTEM = 'DATA_GENERATOR',
      GOVERNANCE.CATALOG.CERTIFICATION = 'IN_PROGRESS',
      GOVERNANCE.CATALOG.DATA_OWNER = 'Finance';

-- ============================================
-- TAG SENSITIVE/CDE COLUMNS
--
-- CLASSIFICATION is intentionally not set here. It is assigned only by
-- classification/10_sync_confirmed_classification_tags.sql after a steward
-- approves a review decision.
-- ============================================

ALTER TABLE RAW.PUBLIC.CUSTOMER MODIFY COLUMN TAX_ID SET TAG 
  GOVERNANCE.CATALOG.MASKING_REQUIRED = 'YES',
  GOVERNANCE.CATALOG.CDE = 'YES',
  GOVERNANCE.CATALOG.CDE_TIER = '1';

ALTER TABLE RAW.PUBLIC.CUSTOMER MODIFY COLUMN DATE_OF_BIRTH SET TAG 
  GOVERNANCE.CATALOG.MASKING_REQUIRED = 'YES';

ALTER TABLE RAW.PUBLIC.CUSTOMER MODIFY COLUMN EMAIL SET TAG 
  GOVERNANCE.CATALOG.MASKING_REQUIRED = 'YES';

ALTER TABLE RAW.PUBLIC.CUSTOMER MODIFY COLUMN PHONE SET TAG 
  GOVERNANCE.CATALOG.MASKING_REQUIRED = 'YES';

ALTER TABLE RAW.PUBLIC.ACCOUNT MODIFY COLUMN ACCOUNT_NUMBER SET TAG 
  GOVERNANCE.CATALOG.MASKING_REQUIRED = 'YES',
  GOVERNANCE.CATALOG.CDE = 'YES',
  GOVERNANCE.CATALOG.CDE_TIER = '1';

ALTER TABLE RAW.PUBLIC.ACCOUNT MODIFY COLUMN BALANCE SET TAG 
  GOVERNANCE.CATALOG.CDE = 'YES',
  GOVERNANCE.CATALOG.CDE_TIER = '1';

ALTER TABLE RAW.PUBLIC.ACCOUNT MODIFY COLUMN ACCOUNT_ID SET TAG 
  GOVERNANCE.CATALOG.CDE = 'YES',
  GOVERNANCE.CATALOG.CDE_TIER = '1';

ALTER TABLE RAW.PUBLIC.TRANSACTION MODIFY COLUMN TRANSACTION_ID SET TAG 
  GOVERNANCE.CATALOG.CDE = 'YES',
  GOVERNANCE.CATALOG.CDE_TIER = '1';

ALTER TABLE RAW.PUBLIC.CUSTOMER MODIFY COLUMN CUSTOMER_ID SET TAG 
  GOVERNANCE.CATALOG.CDE = 'YES',
  GOVERNANCE.CATALOG.CDE_TIER = '1';

SELECT '✓ Tags applied to tables and columns' as status;
