-- metadata/create_metadata_store.sql
-- Create foundation for storing harvested metadata
-- Run as: snow sql -f metadata/create_metadata_store.sql

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

-- ============================================
-- 1. TABLE METADATA (Harvested from INFORMATION_SCHEMA)
-- ============================================
CREATE TABLE IF NOT EXISTS TABLE_METADATA (
  DATABASE_NAME VARCHAR,
  SCHEMA_NAME VARCHAR,
  TABLE_NAME VARCHAR NOT NULL,
  OBJECT_TYPE VARCHAR,  -- TABLE, VIEW, DYNAMIC TABLE
  TABLE_COMMENT VARCHAR,
  ROW_COUNT BIGINT,
  CREATED_ON TIMESTAMP_NTZ,
  LAST_ALTERED TIMESTAMP_NTZ,
  HARVESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (DATABASE_NAME, SCHEMA_NAME, TABLE_NAME)
);

-- ============================================
-- 2. COLUMN METADATA (Harvested from INFORMATION_SCHEMA)
-- ============================================
CREATE TABLE IF NOT EXISTS COLUMN_METADATA (
  DATABASE_NAME VARCHAR,
  SCHEMA_NAME VARCHAR,
  TABLE_NAME VARCHAR,
  ORDINAL_POSITION INTEGER,
  COLUMN_NAME VARCHAR NOT NULL,
  COLUMN_TYPE VARCHAR,
  COLUMN_COMMENT VARCHAR,
  IS_NULLABLE VARCHAR,
  HARVESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, COLUMN_NAME)
);

-- ============================================
-- 3. DATA DICTIONARY (Loaded from CSV)
-- ============================================
CREATE TABLE IF NOT EXISTS DATA_DICTIONARY (
  TABLE_NAME VARCHAR,
  COLUMN_NAME VARCHAR,
  COLUMN_DESCRIPTION VARCHAR,
  DATA_TYPE VARCHAR,
  SENSITIVITY_CLASSIFICATION VARCHAR,
  IS_CDE BOOLEAN,
  NOTES VARCHAR,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (TABLE_NAME, COLUMN_NAME)
);

-- ============================================
-- 4. BANKING GLOSSARY (Business Metadata)
-- ============================================
CREATE TABLE IF NOT EXISTS BANKING_GLOSSARY (
  TERM_ID INTEGER,
  TERM_NAME VARCHAR NOT NULL,
  DEFINITION VARCHAR NOT NULL,
  BUSINESS_DOMAIN VARCHAR,
  SYNONYMS VARCHAR,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (TERM_ID)
);

-- ============================================
-- 5. GLOSSARY TERM MAPPINGS (Links terms to columns)
-- ============================================
CREATE TABLE IF NOT EXISTS GLOSSARY_TERM_MAPPINGS (
  DATABASE_NAME VARCHAR,
  SCHEMA_NAME VARCHAR,
  TABLE_NAME VARCHAR,
  COLUMN_NAME VARCHAR,
  TERM_ID INTEGER,
  MAPPED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, COLUMN_NAME, TERM_ID)
);

-- ============================================
-- 6. CDE REGISTRY (Critical Data Elements)
-- ============================================
CREATE TABLE IF NOT EXISTS CDE_REGISTRY (
  CDE_ID INTEGER,
  DATABASE_NAME VARCHAR,
  SCHEMA_NAME VARCHAR,
  TABLE_NAME VARCHAR,
  COLUMN_NAME VARCHAR,
  CDE_NAME VARCHAR NOT NULL,
  CRITICALITY_LEVEL VARCHAR,  -- CRITICAL, HIGH, MEDIUM
  BUSINESS_OWNER VARCHAR,
  DESCRIPTION VARCHAR,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (CDE_ID)
);

-- ============================================
-- 7. TAG METADATA TRACKING
-- ============================================
CREATE TABLE IF NOT EXISTS TAG_ASSIGNMENTS_HISTORY (
  TAG_NAME VARCHAR,
  OBJECT_TYPE VARCHAR,  -- COLUMN, TABLE, DATABASE, SCHEMA
  OBJECT_IDENTIFIER VARCHAR,
  TAG_VALUE VARCHAR,
  ASSIGNED_BY VARCHAR,
  ASSIGNED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  HARVEST_ID VARCHAR
);

-- Verify tables created
SHOW TABLES IN GOVERNANCE.CATALOG;
SELECT '✓ Metadata store created' as status;
