USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE OR REPLACE VIEW CATALOG_MASTER_VIEW AS

WITH cde AS (
    SELECT
        DATABASE_NAME,
        SCHEMA_NAME,
        TABLE_NAME,
        COLUMN_NAME,
        'YES' AS CDE_FLAG,
        CRITICALITY_LEVEL,
        BUSINESS_OWNER
    FROM GOVERNANCE.CATALOG.CDE_REGISTRY
),

latest_dq_invocation AS (
    SELECT INVOCATION_ID
    FROM GOVERNANCE.CATALOG.DQ_RESULT
    WHERE INVOCATION_ID IS NOT NULL
    GROUP BY INVOCATION_ID
    ORDER BY MAX(EXECUTED_AT) DESC
    LIMIT 1
),

mart_dq AS (
    SELECT
        TARGET_TABLE,
        CASE
            WHEN COUNT_IF(CHECK_RESULT <> 'PASS') = 0
             AND COUNT(*) = 6
            THEN 'PASS'
            ELSE 'FAIL'
        END AS LATEST_DQ_STATUS,
        MAX(EXECUTED_AT) AS LATEST_DQ_RUN
    FROM GOVERNANCE.CATALOG.DQ_RESULT r
    JOIN latest_dq_invocation l
      ON r.INVOCATION_ID = l.INVOCATION_ID
    GROUP BY TARGET_TABLE
),

tag_values AS (
    SELECT
        OBJECT_DATABASE AS DATABASE_NAME,
        OBJECT_SCHEMA AS SCHEMA_NAME,
        OBJECT_NAME AS TABLE_NAME,

        MAX(
            CASE
                WHEN TAG_NAME = 'DATA_OWNER'
                THEN TAG_VALUE
            END
        ) AS DATA_OWNER,

        MAX(
            CASE
                WHEN TAG_NAME = 'DATA_STEWARD'
                THEN TAG_VALUE
            END
        ) AS DATA_STEWARD,

        MAX(
            CASE
                WHEN TAG_NAME = 'CERTIFICATION'
                THEN TAG_VALUE
            END
        ) AS CERTIFICATION

    FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES

    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'CATALOG'
      AND DOMAIN IN ('TABLE', 'VIEW')

    GROUP BY
        OBJECT_DATABASE,
        OBJECT_SCHEMA,
        OBJECT_NAME
)

SELECT
    cm.DATABASE_NAME,
    cm.SCHEMA_NAME,
    cm.TABLE_NAME,
    cm.COLUMN_NAME,
    cm.ORDINAL_POSITION,
    cm.COLUMN_TYPE,
    cm.IS_NULLABLE,

    COALESCE(
        NULLIF(cm.COLUMN_COMMENT, ''),
        NULLIF(dd.COLUMN_DESCRIPTION, '')
    ) AS DESCRIPTION,

    COALESCE(c.CDE_FLAG, 'NO') AS CDE_FLAG,
    c.CRITICALITY_LEVEL,

    COALESCE(tv.DATA_OWNER, c.BUSINESS_OWNER) AS DATA_OWNER,
    tv.DATA_STEWARD,
    tv.CERTIFICATION,

    CAST(NULL AS VARCHAR) AS CLASSIFICATION,

    CASE
        WHEN UPPER(cm.TABLE_NAME) = 'MART_DEPOSITS'
        THEN dq.LATEST_DQ_STATUS
        ELSE NULL
    END AS LATEST_DQ_STATUS,

    CASE
        WHEN UPPER(cm.TABLE_NAME) = 'MART_DEPOSITS'
        THEN dq.LATEST_DQ_RUN
        ELSE NULL
    END AS LATEST_DQ_RUN,

    cm.HARVESTED_AT AS LAST_METADATA_REFRESH,

    CAST(NULL AS VARCHAR) AS UPSTREAM_SOURCE,
    CAST(NULL AS NUMBER) AS QUERY_COUNT,
    CAST(NULL AS NUMBER) AS DISTINCT_ROLES

FROM GOVERNANCE.CATALOG.COLUMN_METADATA cm

LEFT JOIN GOVERNANCE.CATALOG.DATA_DICTIONARY dd
  ON UPPER(cm.TABLE_NAME) = UPPER(dd.TABLE_NAME)
 AND UPPER(cm.COLUMN_NAME) = UPPER(dd.COLUMN_NAME)

LEFT JOIN cde c
  ON UPPER(cm.DATABASE_NAME) = UPPER(c.DATABASE_NAME)
 AND UPPER(cm.SCHEMA_NAME) = UPPER(c.SCHEMA_NAME)
 AND UPPER(cm.TABLE_NAME) = UPPER(c.TABLE_NAME)
 AND UPPER(cm.COLUMN_NAME) = UPPER(c.COLUMN_NAME)

LEFT JOIN tag_values tv
  ON UPPER(cm.DATABASE_NAME) = UPPER(tv.DATABASE_NAME)
 AND UPPER(cm.SCHEMA_NAME) = UPPER(tv.SCHEMA_NAME)
 AND UPPER(cm.TABLE_NAME) = UPPER(tv.TABLE_NAME)

LEFT JOIN mart_dq dq
  ON UPPER(dq.TARGET_TABLE) = UPPER(cm.TABLE_NAME);