-- metadata/harvest_metadata_task.sql
-- PROCEDURE + TASK: Automated metadata harvesting

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

-- ============================================
-- 1. CREATE PROCEDURE
-- ============================================
CREATE OR REPLACE PROCEDURE HARVEST_METADATA_PROC()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
  -- HARVEST TABLE METADATA
  MERGE INTO TABLE_METADATA t
  USING (
    SELECT 
      TABLE_CATALOG as DATABASE_NAME,
      TABLE_SCHEMA as SCHEMA_NAME,
      TABLE_NAME,
      TABLE_TYPE as OBJECT_TYPE,
      CREATED as CREATED_ON,
      LAST_ALTERED
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_CATALOG IN ('RAW', 'ANALYTICS', 'GOVERNANCE')
      AND TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA', 'ACCOUNT_USAGE')
  ) s
  ON t.DATABASE_NAME = s.DATABASE_NAME 
    AND t.SCHEMA_NAME = s.SCHEMA_NAME 
    AND t.TABLE_NAME = s.TABLE_NAME
  WHEN MATCHED THEN
    UPDATE SET 
      t.HARVESTED_AT = CURRENT_TIMESTAMP(),
      t.LAST_ALTERED = s.LAST_ALTERED
  WHEN NOT MATCHED THEN
    INSERT (DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, OBJECT_TYPE, 
            ROW_COUNT, CREATED_ON, LAST_ALTERED, HARVESTED_AT)
    VALUES (s.DATABASE_NAME, s.SCHEMA_NAME, s.TABLE_NAME, s.OBJECT_TYPE, 
            0, s.CREATED_ON, s.LAST_ALTERED, CURRENT_TIMESTAMP());
  
  -- HARVEST COLUMN METADATA
  MERGE INTO COLUMN_METADATA c
  USING (
    SELECT 
      TABLE_CATALOG as DATABASE_NAME,
      TABLE_SCHEMA as SCHEMA_NAME,
      TABLE_NAME,
      ORDINAL_POSITION,
      COLUMN_NAME,
      DATA_TYPE as COLUMN_TYPE,
      COMMENT as COLUMN_COMMENT,
      IS_NULLABLE
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_CATALOG IN ('RAW', 'ANALYTICS', 'GOVERNANCE')
      AND TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA', 'ACCOUNT_USAGE')
  ) s
  ON c.DATABASE_NAME = s.DATABASE_NAME 
    AND c.SCHEMA_NAME = s.SCHEMA_NAME 
    AND c.TABLE_NAME = s.TABLE_NAME 
    AND c.COLUMN_NAME = s.COLUMN_NAME
  WHEN MATCHED THEN
    UPDATE SET 
      c.HARVESTED_AT = CURRENT_TIMESTAMP(),
      c.COLUMN_COMMENT = s.COLUMN_COMMENT,
      c.COLUMN_TYPE = s.COLUMN_TYPE
  WHEN NOT MATCHED THEN
    INSERT (DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, ORDINAL_POSITION, COLUMN_NAME, 
            COLUMN_TYPE, COLUMN_COMMENT, IS_NULLABLE, HARVESTED_AT)
    VALUES (s.DATABASE_NAME, s.SCHEMA_NAME, s.TABLE_NAME, s.ORDINAL_POSITION, 
            s.COLUMN_NAME, s.COLUMN_TYPE, s.COLUMN_COMMENT, s.IS_NULLABLE, CURRENT_TIMESTAMP());
  
  -- LOG HARVEST EVENT
  INSERT INTO TAG_ASSIGNMENTS_HISTORY (
    TAG_NAME, OBJECT_TYPE, OBJECT_IDENTIFIER, TAG_VALUE,
    ASSIGNED_BY, ASSIGNED_AT, HARVEST_ID
  )
  VALUES (
    'HARVEST_LOG', 
    'PROCEDURE', 
    'HARVEST_METADATA_PROC',
    'Harvest completed successfully',
    'SVC_PIPELINE', 
    CURRENT_TIMESTAMP(), 
    TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYY_MM_DD_HH24_MI_SS')
  );
  
  RETURN 'Harvest complete at ' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYY-MM-DD HH24:MI:SS');
END;
$$;

-- Test the procedure
CALL HARVEST_METADATA_PROC();

-- ============================================
-- 2. CREATE TASK (Scheduled daily)
-- ============================================
CREATE OR REPLACE TASK HARVEST_METADATA_TASK
  WAREHOUSE = 'TRANSFORM_WH'
  SCHEDULE = 'USING CRON 0 2 * * * UTC'
  COMMENT = 'Harvest metadata from INFORMATION_SCHEMA daily at 2 AM UTC'
AS
  CALL HARVEST_METADATA_PROC();

-- Enable task
ALTER TASK HARVEST_METADATA_TASK RESUME;

-- Verify
SHOW TASKS IN DATABASE GOVERNANCE;

SELECT '✓ Harvest procedure and scheduled task created' as status;
