USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

MERGE INTO GOVERNANCE.CATALOG.DATA_DICTIONARY AS T
USING (

    SELECT * FROM VALUES

    ('MART_DEPOSITS', 'ACCOUNT_ID',
     'Unique identifier for the deposit account.',
     'TEXT', NULL, FALSE,
     'Primary account identifier used across the certified deposits mart.'),

    ('MART_DEPOSITS', 'CUSTOMER_ID',
     'Unique identifier for the customer associated with the account.',
     'TEXT', NULL, FALSE,
     'Links the deposit account to the customer entity.'),

    ('MART_DEPOSITS', 'ACCOUNT_NUMBER',
     'Business account number associated with the deposit account.',
     'NUMBER', 'ACCOUNT_DETAILS', FALSE,
     'Sensitive account identifier.'),

    ('MART_DEPOSITS', 'ACCOUNT_TYPE',
     'Type of deposit account, such as checking or savings.',
     'TEXT', NULL, FALSE,
     'Used for account-level reporting and reconciliation.'),

    ('MART_DEPOSITS', 'STATUS',
     'Current status of the deposit account.',
     'TEXT', NULL, FALSE,
     'Indicates whether the account is active or otherwise.'),

    ('MART_DEPOSITS', 'BRANCH_CODE',
     'Code identifying the branch associated with the deposit account.',
     'TEXT', NULL, FALSE,
     'Used for branch-level reporting and row access control.'),

    ('MART_DEPOSITS', 'OPENED_DATE',
     'Date on which the deposit account was opened.',
     'TEXT', NULL, FALSE,
     'Source account opening date.'),

    ('MART_DEPOSITS', 'CURRENT_BALANCE',
     'Current balance of the deposit account.',
     'FLOAT', NULL, FALSE,
     'Certified account balance measure.'),

    ('MART_DEPOSITS', 'FIRST_NAME',
     'Customer first name.',
     'TEXT', 'PII', FALSE,
     'Personally identifiable customer attribute.'),

    ('MART_DEPOSITS', 'LAST_NAME',
     'Customer last name.',
     'TEXT', 'PII', FALSE,
     'Personally identifiable customer attribute.'),

    ('MART_DEPOSITS', 'EMAIL',
     'Customer email address.',
     'TEXT', 'PII', FALSE,
     'Personally identifiable customer contact attribute.'),

    ('MART_DEPOSITS', 'CUSTOMER_TYPE',
     'Business classification of the customer.',
     'TEXT', NULL, FALSE,
     'Examples may include individual or business customer types.'),

    ('MART_DEPOSITS', 'TAX_ID',
     'Customer tax identifier.',
     'TEXT', 'PII', FALSE,
     'Sensitive customer identifier.'),

    ('MART_DEPOSITS', 'LATEST_BUSINESS_DATE',
     'Most recent valid staged transaction business date associated with the account.',
     'TEXT', NULL, FALSE,
     'Used to represent the latest business activity date in the mart.'),

    ('MART_DEPOSITS', 'TRANSACTION_COUNT',
     'Number of qualifying transactions associated with the account.',
     'NUMBER', NULL, FALSE,
     'Aggregated transaction count for the deposit account.'),

    ('MART_DEPOSITS', 'TOTAL_DEBITS',
     'Total debit transaction amount for the deposit account.',
     'FLOAT', NULL, FALSE,
     'Derived using debit transactions from staged transaction data.'),

    ('MART_DEPOSITS', 'TOTAL_CREDITS',
     'Total credit transaction amount for the deposit account.',
     'FLOAT', NULL, FALSE,
     'Certified total-deposits measure derived from credit transactions.'),

    ('MART_DEPOSITS', 'DBT_REFRESHED_AT',
     'Timestamp when the dbt model was last refreshed.',
     'TIMESTAMP_LTZ', NULL, FALSE,
     'Technical refresh metadata generated by the dbt pipeline.'),

    ('MART_DEPOSITS', 'DBT_BUSINESS_DATE',
     'Business date associated with the dbt mart refresh.',
     'DATE', NULL, FALSE,
     'Technical business-date marker used for mart processing.'),

    ('MART_DEPOSITS', 'MART_NAME',
     'Name of the certified mart producing the record.',
     'TEXT', NULL, FALSE,
     'Technical lineage and identification attribute.')

    AS S(
        TABLE_NAME,
        COLUMN_NAME,
        COLUMN_DESCRIPTION,
        DATA_TYPE,
        SENSITIVITY_CLASSIFICATION,
        IS_CDE,
        NOTES
    )

) AS S

ON UPPER(T.TABLE_NAME) = UPPER(S.TABLE_NAME)
AND UPPER(T.COLUMN_NAME) = UPPER(S.COLUMN_NAME)

WHEN MATCHED THEN UPDATE SET
    T.COLUMN_DESCRIPTION = S.COLUMN_DESCRIPTION,
    T.DATA_TYPE = S.DATA_TYPE,
    T.SENSITIVITY_CLASSIFICATION = S.SENSITIVITY_CLASSIFICATION,
    T.IS_CDE = S.IS_CDE,
    T.NOTES = S.NOTES,
    T.LOADED_AT = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (
    TABLE_NAME,
    COLUMN_NAME,
    COLUMN_DESCRIPTION,
    DATA_TYPE,
    SENSITIVITY_CLASSIFICATION,
    IS_CDE,
    NOTES,
    LOADED_AT
)
VALUES (
    S.TABLE_NAME,
    S.COLUMN_NAME,
    S.COLUMN_DESCRIPTION,
    S.DATA_TYPE,
    S.SENSITIVITY_CLASSIFICATION,
    S.IS_CDE,
    S.NOTES,
    CURRENT_TIMESTAMP()
);