-- lineage/01_permissions.sql
-- Account-level grants below are one-time grants, normally executed by an
-- account administrator. Operational lineage scripts run as DATA_OWNER.

GRANT VIEW LINEAGE ON ACCOUNT TO ROLE DATA_OWNER;
GRANT DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER TO ROLE DATA_OWNER;
GRANT DATABASE ROLE SNOWFLAKE.OBJECT_VIEWER TO ROLE DATA_OWNER;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE DATA_OWNER;

GRANT USAGE ON DATABASE GOVERNANCE TO ROLE DATA_OWNER;
GRANT USAGE ON SCHEMA GOVERNANCE.CATALOG TO ROLE DATA_OWNER;
GRANT CREATE TABLE ON SCHEMA GOVERNANCE.CATALOG TO ROLE DATA_OWNER;
GRANT CREATE PROCEDURE ON SCHEMA GOVERNANCE.CATALOG TO ROLE DATA_OWNER;
GRANT CREATE TASK ON SCHEMA GOVERNANCE.CATALOG TO ROLE DATA_OWNER;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE DATA_OWNER;
