-- lineage/02_create_lineage_tables.sql

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE TABLE IF NOT EXISTS LINEAGE_EDGE (
  SOURCE_DATABASE VARCHAR,
  SOURCE_SCHEMA VARCHAR,
  SOURCE_OBJECT VARCHAR,
  SOURCE_OBJECT_DOMAIN VARCHAR,
  SOURCE_COLUMN VARCHAR,
  TARGET_DATABASE VARCHAR,
  TARGET_SCHEMA VARCHAR,
  TARGET_OBJECT VARCHAR,
  TARGET_OBJECT_DOMAIN VARCHAR,
  TARGET_COLUMN VARCHAR,
  DIRECTION VARCHAR,
  DISTANCE NUMBER,
  LINEAGE_SOURCE VARCHAR NOT NULL,
  RELATIONSHIP_TYPE VARCHAR,
  PROCESS_ID VARCHAR,
  QUERY_ID VARCHAR,
  QUERY_START_TIME TIMESTAMP_LTZ,
  PROCESS_DETAILS VARIANT,
  CAPTURED_AT TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS GOVERNANCE.CATALOG.LINEAGE_EDGE_EXTERNAL (
    SOURCE_SYSTEM       VARCHAR NOT NULL,
    SOURCE_OBJECT       VARCHAR NOT NULL,
    SOURCE_COLUMN       VARCHAR,
    TARGET_SYSTEM       VARCHAR NOT NULL,
    TARGET_OBJECT       VARCHAR NOT NULL,
    TARGET_COLUMN       VARCHAR,
    RELATIONSHIP_TYPE   VARCHAR NOT NULL,
    REGISTRATION_TYPE   VARCHAR NOT NULL,
    NOTES               VARCHAR,
    CREATED_AT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
