-- lineage/03_refresh_lineage_snapshot.sql
-- Native GET_LINEAGE is authoritative. Account Usage inserts are supplemental
-- and may legitimately insert zero rows because those views have latency.

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE OR REPLACE PROCEDURE REFRESH_LINEAGE_SNAPSHOT()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
  -- This snapshot is deterministic for the canonical MART_DEPOSITS anchors.
  DELETE FROM GOVERNANCE.CATALOG.LINEAGE_EDGE;

  INSERT INTO GOVERNANCE.CATALOG.LINEAGE_EDGE (
    SOURCE_DATABASE, SOURCE_SCHEMA, SOURCE_OBJECT, SOURCE_OBJECT_DOMAIN, SOURCE_COLUMN,
    TARGET_DATABASE, TARGET_SCHEMA, TARGET_OBJECT, TARGET_OBJECT_DOMAIN, TARGET_COLUMN,
    DIRECTION, DISTANCE, LINEAGE_SOURCE, RELATIONSHIP_TYPE,
    PROCESS_ID, QUERY_ID, QUERY_START_TIME, PROCESS_DETAILS, CAPTURED_AT
  )
  SELECT
    SOURCE_OBJECT_DATABASE, SOURCE_OBJECT_SCHEMA, SOURCE_OBJECT_NAME,
    SOURCE_OBJECT_DOMAIN, SOURCE_COLUMN_NAME,
    TARGET_OBJECT_DATABASE, TARGET_OBJECT_SCHEMA, TARGET_OBJECT_NAME,
    TARGET_OBJECT_DOMAIN, TARGET_COLUMN_NAME,
    DIRECTION, DISTANCE, 'SNOWFLAKE_GET_LINEAGE', 'NATIVE',
    COALESCE(PROCESS:query_id::VARCHAR, PROCESS:QUERY_ID::VARCHAR),
    COALESCE(PROCESS:query_id::VARCHAR, PROCESS:QUERY_ID::VARCHAR),
    NULL, PROCESS, CURRENT_TIMESTAMP()
  FROM (
    SELECT 'UPSTREAM' AS DIRECTION, *
    FROM TABLE(SNOWFLAKE.CORE.GET_LINEAGE(
      'ANALYTICS.MARTS.MART_DEPOSITS', 'TABLE', 'UPSTREAM', 5
    ))
    UNION ALL
    SELECT 'DOWNSTREAM' AS DIRECTION, *
    FROM TABLE(SNOWFLAKE.CORE.GET_LINEAGE(
      'ANALYTICS.MARTS.MART_DEPOSITS', 'TABLE', 'DOWNSTREAM', 5
    ))
    UNION ALL
    SELECT 'UPSTREAM' AS DIRECTION, *
    FROM TABLE(SNOWFLAKE.CORE.GET_LINEAGE(
      object_name => 'ANALYTICS.MARTS.MART_DEPOSITS.TOTAL_CREDITS',
      object_domain => 'COLUMN', direction => 'UPSTREAM', max_distance => 5
    ))
    UNION ALL
    SELECT 'UPSTREAM' AS DIRECTION, *
    FROM TABLE(SNOWFLAKE.CORE.GET_LINEAGE(
      object_name => 'ANALYTICS.MARTS.MART_DEPOSITS.TOTAL_DEBITS',
      object_domain => 'COLUMN', direction => 'UPSTREAM', max_distance => 5
    ))
    UNION ALL
    SELECT 'UPSTREAM' AS DIRECTION, *
    FROM TABLE(SNOWFLAKE.CORE.GET_LINEAGE(
      object_name => 'ANALYTICS.MARTS.MART_DEPOSITS.BRANCH_CODE',
      object_domain => 'COLUMN', direction => 'UPSTREAM', max_distance => 5
    ))
    UNION ALL
    SELECT 'UPSTREAM' AS DIRECTION, *
    FROM TABLE(SNOWFLAKE.CORE.GET_LINEAGE(
      object_name => 'ANALYTICS.MARTS.MART_DEPOSITS.CURRENT_BALANCE',
      object_domain => 'COLUMN', direction => 'UPSTREAM', max_distance => 5
    ))
  );

  -- OBJECT_DEPENDENCIES is retained as supplemental metadata. In this
  -- materialized dbt path it can validly return zero rows.
  INSERT INTO GOVERNANCE.CATALOG.LINEAGE_EDGE (
    SOURCE_DATABASE, SOURCE_SCHEMA, SOURCE_OBJECT, SOURCE_OBJECT_DOMAIN,
    TARGET_DATABASE, TARGET_SCHEMA, TARGET_OBJECT, TARGET_OBJECT_DOMAIN,
    DIRECTION, DISTANCE, LINEAGE_SOURCE, RELATIONSHIP_TYPE, CAPTURED_AT
  )
  SELECT
    REFERENCED_DATABASE, REFERENCED_SCHEMA, REFERENCED_OBJECT_NAME, REFERENCED_OBJECT_DOMAIN,
    REFERENCING_DATABASE, REFERENCING_SCHEMA, REFERENCING_OBJECT_NAME, REFERENCING_OBJECT_DOMAIN,
    IFF(REFERENCING_DATABASE = 'ANALYTICS' AND REFERENCING_SCHEMA = 'MARTS'
        AND REFERENCING_OBJECT_NAME = 'MART_DEPOSITS', 'UPSTREAM', 'DOWNSTREAM'),
    1, 'OBJECT_DEPENDENCIES', DEPENDENCY_TYPE, CURRENT_TIMESTAMP()
  FROM SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES
  WHERE (REFERENCING_DATABASE = 'ANALYTICS' AND REFERENCING_SCHEMA = 'MARTS'
         AND REFERENCING_OBJECT_NAME = 'MART_DEPOSITS')
     OR (REFERENCED_DATABASE = 'ANALYTICS' AND REFERENCED_SCHEMA = 'MARTS'
         AND REFERENCED_OBJECT_NAME = 'MART_DEPOSITS');

  -- Runtime evidence is supplemental only. A missing or delayed Access History
  -- record never determines whether this refresh succeeds.
  INSERT INTO GOVERNANCE.CATALOG.LINEAGE_EDGE (
    SOURCE_DATABASE, SOURCE_SCHEMA, SOURCE_OBJECT, SOURCE_OBJECT_DOMAIN,
    TARGET_DATABASE, TARGET_SCHEMA, TARGET_OBJECT, TARGET_OBJECT_DOMAIN,
    DIRECTION, DISTANCE, LINEAGE_SOURCE, RELATIONSHIP_TYPE,
    QUERY_ID, QUERY_START_TIME, PROCESS_DETAILS, CAPTURED_AT
  )
  SELECT DISTINCT
    SPLIT_PART(S.VALUE:objectName::VARCHAR, '.', 1),
    SPLIT_PART(S.VALUE:objectName::VARCHAR, '.', 2),
    SPLIT_PART(S.VALUE:objectName::VARCHAR, '.', 3),
    S.VALUE:objectDomain::VARCHAR,
    'ANALYTICS', 'MARTS', 'MART_DEPOSITS', 'TABLE',
    'UPSTREAM', 1, 'ACCESS_HISTORY', 'RUNTIME_QUERY',
    H.QUERY_ID, H.QUERY_START_TIME, OBJECT_CONSTRUCT(
      'source_columns', S.VALUE:columns,
      'target_columns', T.VALUE:columns
    ), CURRENT_TIMESTAMP()
  FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY AS H,
       LATERAL FLATTEN(INPUT => H.DIRECT_OBJECTS_ACCESSED) AS S,
       LATERAL FLATTEN(INPUT => H.OBJECTS_MODIFIED) AS T
  WHERE T.VALUE:objectName::VARCHAR = 'ANALYTICS.MARTS.MART_DEPOSITS';

  RETURN 'Lineage snapshot refreshed at ' || CURRENT_TIMESTAMP();
END;
$$;

CALL GOVERNANCE.CATALOG.REFRESH_LINEAGE_SNAPSHOT();
