-- lineage/04_create_lineage_task.sql

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE OR REPLACE TASK REFRESH_LINEAGE_SNAPSHOT_TASK
  WAREHOUSE = TRANSFORM_WH
  SCHEDULE = 'USING CRON 0 3 * * * UTC'
  COMMENT = 'Daily native and supplemental lineage snapshot for MART_DEPOSITS'
AS
  CALL GOVERNANCE.CATALOG.REFRESH_LINEAGE_SNAPSHOT();

-- Tasks are created suspended. Enable only after reviewing the first manual
-- refresh: ALTER TASK GOVERNANCE.CATALOG.REFRESH_LINEAGE_SNAPSHOT_TASK RESUME;
-- To pause: ALTER TASK GOVERNANCE.CATALOG.REFRESH_LINEAGE_SNAPSHOT_TASK SUSPEND;
