-- lineage/06_native_lineage_queries.sql

USE ROLE DATA_OWNER;

-- Primary table-level upstream and downstream evidence.
SELECT * FROM TABLE(SNOWFLAKE.CORE.GET_LINEAGE(
  'ANALYTICS.MARTS.MART_DEPOSITS', 'TABLE', 'UPSTREAM', 5
));
SELECT * FROM TABLE(SNOWFLAKE.CORE.GET_LINEAGE(
  'ANALYTICS.MARTS.MART_DEPOSITS', 'TABLE', 'DOWNSTREAM', 5
));

-- Primary column-level evidence for certified mart measures and branch scope.
SELECT * FROM TABLE(SNOWFLAKE.CORE.GET_LINEAGE(
  object_name => 'ANALYTICS.MARTS.MART_DEPOSITS.TOTAL_CREDITS',
  object_domain => 'COLUMN', direction => 'UPSTREAM', max_distance => 5
));
SELECT * FROM TABLE(SNOWFLAKE.CORE.GET_LINEAGE(
  object_name => 'ANALYTICS.MARTS.MART_DEPOSITS.BRANCH_CODE',
  object_domain => 'COLUMN', direction => 'UPSTREAM', max_distance => 5
));

-- Supplemental only: materialized dbt tables can produce zero dependency rows.
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES
WHERE (REFERENCING_DATABASE = 'ANALYTICS' AND REFERENCING_SCHEMA = 'MARTS'
       AND REFERENCING_OBJECT_NAME = 'MART_DEPOSITS')
   OR (REFERENCED_DATABASE = 'ANALYTICS' AND REFERENCED_SCHEMA = 'MARTS'
       AND REFERENCED_OBJECT_NAME = 'MART_DEPOSITS');

-- Supplemental runtime evidence only; Account Usage latency is expected.
SELECT QUERY_ID, QUERY_START_TIME, DIRECT_OBJECTS_ACCESSED, OBJECTS_MODIFIED
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY AS H,
     LATERAL FLATTEN(INPUT => H.OBJECTS_MODIFIED) AS M
WHERE M.VALUE:objectName::VARCHAR = 'ANALYTICS.MARTS.MART_DEPOSITS'
ORDER BY QUERY_START_TIME DESC
LIMIT 20;
