-- lineage/07_total_deposits_trace.sql
-- TOTAL_CREDITS is the certified total-deposits measure for this assessment.

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE OR REPLACE VIEW TOTAL_CREDITS_LINEAGE_TRACE AS
SELECT
  'SNOWFLAKE_GET_LINEAGE' AS EVIDENCE_TYPE,
  SOURCE_DATABASE, SOURCE_SCHEMA, SOURCE_OBJECT, SOURCE_COLUMN,
  TARGET_DATABASE, TARGET_SCHEMA, TARGET_OBJECT, TARGET_COLUMN,
  DISTANCE,
  'Native lineage returned by GET_LINEAGE when Snowflake exposes the column edge.' AS EVIDENCE_NOTE
FROM GOVERNANCE.CATALOG.LINEAGE_EDGE
WHERE LINEAGE_SOURCE = 'SNOWFLAKE_GET_LINEAGE'
  AND (
    (TARGET_DATABASE = 'ANALYTICS' AND TARGET_SCHEMA = 'MARTS'
     AND TARGET_OBJECT = 'MART_DEPOSITS' AND TARGET_COLUMN = 'TOTAL_CREDITS')
    OR (SOURCE_DATABASE = 'RAW' AND SOURCE_SCHEMA = 'PUBLIC'
        AND SOURCE_OBJECT = 'TRANSACTION'
        AND SOURCE_COLUMN IN ('AMOUNT', 'TRANSACTION_TYPE'))
  )
UNION ALL
SELECT
  'DBT_TRANSFORMATION_EXPRESSION',
  'ANALYTICS', 'STAGING', 'STG_TRANSACTION', 'AMOUNT',
  'ANALYTICS', 'MARTS', 'MART_DEPOSITS', 'TOTAL_CREDITS',
  1,
  'Actual dbt expression: SUM(CASE WHEN TRANSACTION_TYPE = ''CREDIT'' THEN AMOUNT ELSE 0 END).'
UNION ALL
SELECT
  'DBT_TRANSFORMATION_EXPRESSION',
  'ANALYTICS', 'STAGING', 'STG_TRANSACTION', 'TRANSACTION_TYPE',
  'ANALYTICS', 'MARTS', 'MART_DEPOSITS', 'TOTAL_CREDITS',
  1,
  'Actual dbt expression condition: TRANSACTION_TYPE = ''CREDIT''.'
UNION ALL
SELECT
  'DBT_TRANSFORMATION_EXPRESSION',
  'RAW', 'PUBLIC', 'TRANSACTION', 'AMOUNT',
  'ANALYTICS', 'STAGING', 'STG_TRANSACTION', 'AMOUNT',
  1,
  'Actual STG_TRANSACTION projection of RAW.PUBLIC.TRANSACTION.AMOUNT.'
UNION ALL
SELECT
  'DBT_TRANSFORMATION_EXPRESSION',
  'RAW', 'PUBLIC', 'TRANSACTION', 'TRANSACTION_TYPE',
  'ANALYTICS', 'STAGING', 'STG_TRANSACTION', 'TRANSACTION_TYPE',
  1,
  'Actual STG_TRANSACTION projection/filter input from RAW.PUBLIC.TRANSACTION.TRANSACTION_TYPE.';

SELECT *
FROM GOVERNANCE.CATALOG.TOTAL_CREDITS_LINEAGE_TRACE
ORDER BY EVIDENCE_TYPE, DISTANCE, SOURCE_DATABASE, SOURCE_SCHEMA, SOURCE_OBJECT, SOURCE_COLUMN;
