-- lineage/09_validate_lineage.sql
-- Each result is derived from current metadata/snapshots; no PASS/FAIL is
-- hardcoded. TASK metadata is shown directly because Account Usage can lag.

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

SELECT 'native_get_lineage_edges' AS CHECK_NAME, COUNT(*) AS OBSERVED_COUNT
FROM GOVERNANCE.CATALOG.LINEAGE_EDGE
WHERE LINEAGE_SOURCE = 'SNOWFLAKE_GET_LINEAGE'
UNION ALL
SELECT 'mart_upstream_edges', COUNT(*)
FROM GOVERNANCE.CATALOG.LINEAGE_EDGE
WHERE LINEAGE_SOURCE = 'SNOWFLAKE_GET_LINEAGE' AND DIRECTION = 'UPSTREAM'
UNION ALL
SELECT 'mart_downstream_edges', COUNT(*)
FROM GOVERNANCE.CATALOG.LINEAGE_EDGE
WHERE LINEAGE_SOURCE = 'SNOWFLAKE_GET_LINEAGE' AND DIRECTION = 'DOWNSTREAM'
UNION ALL
SELECT 'native_column_edges', COUNT(*)
FROM GOVERNANCE.CATALOG.LINEAGE_EDGE
WHERE LINEAGE_SOURCE = 'SNOWFLAKE_GET_LINEAGE'
  AND (SOURCE_COLUMN IS NOT NULL OR TARGET_COLUMN IS NOT NULL)
UNION ALL
SELECT 'external_talend_edges', COUNT(*)
FROM GOVERNANCE.CATALOG.LINEAGE_EDGE_EXTERNAL
WHERE SOURCE_SYSTEM = 'TALEND_LEGACY' AND REGISTRATION_TYPE = 'EXTERNAL_MANUAL'
UNION ALL
SELECT 'external_power_bi_edges', COUNT(*)
FROM GOVERNANCE.CATALOG.LINEAGE_EDGE_EXTERNAL
WHERE TARGET_SYSTEM = 'POWER_BI' AND REGISTRATION_TYPE = 'EXTERNAL_MANUAL'
UNION ALL
SELECT 'total_credits_trace_raw_transaction_inputs', COUNT(*)
FROM GOVERNANCE.CATALOG.TOTAL_CREDITS_LINEAGE_TRACE
WHERE SOURCE_DATABASE = 'RAW' AND SOURCE_SCHEMA = 'PUBLIC'
  AND SOURCE_OBJECT = 'TRANSACTION'
  AND SOURCE_COLUMN IN ('AMOUNT', 'TRANSACTION_TYPE')
UNION ALL
SELECT 'branch_code_downstream_impacts', COUNT(*)
FROM GOVERNANCE.CATALOG.BRANCH_CODE_IMPACT_ANALYSIS;

SHOW TASKS LIKE 'REFRESH_LINEAGE_SNAPSHOT_TASK' IN SCHEMA GOVERNANCE.CATALOG;
