-- certification/01_create_certification_tables.sql

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE TABLE IF NOT EXISTS CERTIFICATION_SCORECARD (
    CERTIFICATION_RUN_ID VARCHAR NOT NULL,
    DATABASE_NAME VARCHAR NOT NULL,
    SCHEMA_NAME VARCHAR NOT NULL,
    OBJECT_NAME VARCHAR NOT NULL,

    CONTROL_NAME VARCHAR NOT NULL,
    CONTROL_STATUS VARCHAR NOT NULL,

    EVIDENCE_VALUE VARCHAR,
    EVIDENCE_DETAILS VARCHAR,

    EVALUATED_AT TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CERTIFICATION_RUN (
    CERTIFICATION_RUN_ID VARCHAR NOT NULL,
    DATABASE_NAME VARCHAR NOT NULL,
    SCHEMA_NAME VARCHAR NOT NULL,
    OBJECT_NAME VARCHAR NOT NULL,

    FINAL_STATUS VARCHAR NOT NULL,
    PASSED_CONTROLS NUMBER NOT NULL,
    TOTAL_CONTROLS NUMBER NOT NULL,

    CERTIFIED_BY VARCHAR,
    STARTED_AT TIMESTAMP_LTZ,
    COMPLETED_AT TIMESTAMP_LTZ
);