-- certification/02_refresh_adoption_evidence.sql
-- Captures recent consumer usage of MART_DEPOSITS from live Information Schema
-- query history, outside the certification stored procedure.

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE TABLE IF NOT EXISTS GOVERNANCE.CATALOG.ADOPTION_EVIDENCE (
    DATABASE_NAME VARCHAR NOT NULL,
    SCHEMA_NAME VARCHAR NOT NULL,
    OBJECT_NAME VARCHAR NOT NULL,

    QUERY_ID VARCHAR NOT NULL,
    ROLE_NAME VARCHAR,
    QUERY_START_TIME TIMESTAMP_LTZ,
    QUERY_TEXT VARCHAR,

    CAPTURED_AT TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

DELETE FROM GOVERNANCE.CATALOG.ADOPTION_EVIDENCE
WHERE DATABASE_NAME = 'ANALYTICS'
  AND SCHEMA_NAME = 'MARTS'
  AND OBJECT_NAME = 'MART_DEPOSITS';

INSERT INTO GOVERNANCE.CATALOG.ADOPTION_EVIDENCE (
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    QUERY_ID,
    ROLE_NAME,
    QUERY_START_TIME,
    QUERY_TEXT,
    CAPTURED_AT
)
SELECT
    'ANALYTICS',
    'MARTS',
    'MART_DEPOSITS',
    QUERY_ID,
    ROLE_NAME,
    START_TIME,
    QUERY_TEXT,
    CURRENT_TIMESTAMP()
FROM TABLE(
    ANALYTICS.INFORMATION_SCHEMA.QUERY_HISTORY(
        END_TIME_RANGE_START => DATEADD(
            'HOUR',
            -167,
            CURRENT_TIMESTAMP()
        ),
        END_TIME_RANGE_END => CURRENT_TIMESTAMP(),
        RESULT_LIMIT => 10000
    )
)
WHERE EXECUTION_STATUS = 'SUCCESS'
  AND QUERY_TEXT ILIKE '%ANALYTICS.MARTS.MART_DEPOSITS%'
  AND ROLE_NAME IN (
      'DEPOSITS_ANALYST',
      'DATA_STEWARD',
      'BRANCH_HUDSON'
  );

SELECT
    ROLE_NAME,
    COUNT(*) AS QUERY_COUNT,
    MAX(QUERY_START_TIME) AS LAST_QUERY_TIME
FROM GOVERNANCE.CATALOG.ADOPTION_EVIDENCE
WHERE DATABASE_NAME = 'ANALYTICS'
  AND SCHEMA_NAME = 'MARTS'
  AND OBJECT_NAME = 'MART_DEPOSITS'
GROUP BY ROLE_NAME
ORDER BY ROLE_NAME;