-- certification/03_create_scorecard_view.sql

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE OR REPLACE VIEW CERTIFICATION_SCORECARD_CURRENT AS

WITH latest_run AS (
    SELECT CERTIFICATION_RUN_ID
    FROM GOVERNANCE.CATALOG.CERTIFICATION_RUN
    WHERE DATABASE_NAME = 'ANALYTICS'
      AND SCHEMA_NAME = 'MARTS'
      AND OBJECT_NAME = 'MART_DEPOSITS'
    ORDER BY COMPLETED_AT DESC
    LIMIT 1
)

SELECT
    S.CONTROL_NAME,
    S.CONTROL_STATUS,
    S.EVIDENCE_VALUE,
    S.EVIDENCE_DETAILS,
    S.EVALUATED_AT
FROM GOVERNANCE.CATALOG.CERTIFICATION_SCORECARD S
JOIN latest_run L
  ON S.CERTIFICATION_RUN_ID = L.CERTIFICATION_RUN_ID
ORDER BY
    CASE S.CONTROL_NAME
        WHEN 'OWNED' THEN 1
        WHEN 'DEFINED' THEN 2
        WHEN 'TRACEABLE' THEN 3
        WHEN 'TRUSTED' THEN 4
        WHEN 'SECURE' THEN 5
        WHEN 'ADOPTED' THEN 6
        WHEN 'RECONCILED' THEN 7
        ELSE 99
    END;