-- certification/03_refresh_certification_evidence.sql

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE TABLE IF NOT EXISTS GOVERNANCE.CATALOG.CERTIFICATION_EVIDENCE (
    DATABASE_NAME VARCHAR NOT NULL,
    SCHEMA_NAME VARCHAR NOT NULL,
    OBJECT_NAME VARCHAR NOT NULL,
    EVIDENCE_TYPE VARCHAR NOT NULL,
    EVIDENCE_KEY VARCHAR,
    EVIDENCE_VALUE VARCHAR,
    CAPTURED_AT TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

DELETE FROM GOVERNANCE.CATALOG.CERTIFICATION_EVIDENCE
WHERE DATABASE_NAME = 'ANALYTICS'
  AND SCHEMA_NAME = 'MARTS'
  AND OBJECT_NAME = 'MART_DEPOSITS'
  AND EVIDENCE_TYPE = 'OWNERSHIP_TAG';

INSERT INTO GOVERNANCE.CATALOG.CERTIFICATION_EVIDENCE (
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    EVIDENCE_TYPE,
    EVIDENCE_KEY,
    EVIDENCE_VALUE,
    CAPTURED_AT
)
SELECT
    'ANALYTICS',
    'MARTS',
    'MART_DEPOSITS',
    'OWNERSHIP_TAG',
    TAG_NAME,
    TAG_VALUE,
    CURRENT_TIMESTAMP()
FROM TABLE(
    ANALYTICS.INFORMATION_SCHEMA.TAG_REFERENCES(
        'ANALYTICS.MARTS.MART_DEPOSITS',
        'TABLE'
    )
)
WHERE UPPER(TAG_DATABASE) = 'GOVERNANCE'
  AND UPPER(TAG_SCHEMA) = 'CATALOG'
  AND UPPER(TAG_NAME) IN (
      'DATA_OWNER',
      'DATA_STEWARD'
  );

SELECT *
FROM GOVERNANCE.CATALOG.CERTIFICATION_EVIDENCE
WHERE DATABASE_NAME = 'ANALYTICS'
  AND SCHEMA_NAME = 'MARTS'
  AND OBJECT_NAME = 'MART_DEPOSITS'
ORDER BY EVIDENCE_TYPE, EVIDENCE_KEY;