USE ROLE ACCOUNTADMIN;

-- Allow DATA_OWNER to work with Snowflake sensitive-data classification.
GRANT DATABASE ROLE SNOWFLAKE.CLASSIFICATION_ADMIN
TO ROLE DATA_OWNER;

-- Allow DATA_OWNER to create a classification-profile instance
-- in GOVERNANCE.CATALOG.
GRANT CREATE SNOWFLAKE.DATA_PRIVACY.CLASSIFICATION_PROFILE
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_OWNER;

-- Needed later for a custom classifier instance.
GRANT CREATE SNOWFLAKE.DATA_PRIVACY.CUSTOM_CLASSIFIER
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_OWNER;

-- DATA_OWNER already operates on the assessment objects, but keep
-- these grants explicit for rebuildability.
GRANT USAGE ON DATABASE GOVERNANCE TO ROLE DATA_OWNER;
GRANT USAGE ON SCHEMA GOVERNANCE.CATALOG TO ROLE DATA_OWNER;

GRANT USAGE ON DATABASE ANALYTICS TO ROLE DATA_OWNER;
GRANT USAGE ON SCHEMA ANALYTICS.STAGING TO ROLE DATA_OWNER;