USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE SNOWFLAKE.DATA_PRIVACY.CLASSIFICATION_PROFILE
IF NOT EXISTS AVIDIA_CLASSIFICATION_PROFILE(
    {
        'minimum_object_age_for_classification_days': 0,
        'maximum_classification_validity_days': 30,
        'auto_tag': true,
        'classify_views': true
    }
);

SELECT AVIDIA_CLASSIFICATION_PROFILE!DESCRIBE();

SHOW SNOWFLAKE.DATA_PRIVACY.CLASSIFICATION_PROFILE
LIKE 'AVIDIA_CLASSIFICATION_PROFILE'
IN SCHEMA GOVERNANCE.CATALOG;