USE ROLE DATA_OWNER;
USE WAREHOUSE TRANSFORM_WH;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE SNOWFLAKE.DATA_PRIVACY.CUSTOM_CLASSIFIER
IF NOT EXISTS AVIDIA_PAN_CLASSIFIER();

CALL AVIDIA_PAN_CLASSIFIER!ADD_REGEX(
    SEMANTIC_CATEGORY => 'CARD_PAN',
    PRIVACY_CATEGORY => 'IDENTIFIER',
    VALUE_REGEX => '.*[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}.*',
    DESCRIPTION => 'Potential card PAN embedded in free-text values',
    THRESHOLD => 0.05
);

-- LIST is a function-like instance method, use SELECT
SELECT AVIDIA_PAN_CLASSIFIER!LIST();

-- Register classifier definition into the profile
CALL AVIDIA_CLASSIFICATION_PROFILE!SET_CUSTOM_CLASSIFIERS(
    {
        'AVIDIA_PAN_CLASSIFIER':
            AVIDIA_PAN_CLASSIFIER!LIST()
    }
);

SELECT AVIDIA_CLASSIFICATION_PROFILE!DESCRIBE();