-- classification/compare_classification_accuracy.sql
-- Compare detected classifications vs sealed baseline from Block 0

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

-- ============================================
-- VIEW: CLASSIFICATION ACCURACY (Detected vs Sealed)
-- ============================================
CREATE OR REPLACE VIEW CLASSIFICATION_ACCURACY_VIEW AS
SELECT 
  d.TABLE_NAME,
  d.COLUMN_NAME,
  d.DETECTED_CLASSIFICATION as detected_class,
  s.SENSITIVITY_CLASSIFICATION as sealed_class,
  CASE 
    WHEN d.DETECTED_CLASSIFICATION = s.SENSITIVITY_CLASSIFICATION THEN 'MATCH'
    WHEN d.DETECTED_CLASSIFICATION IS NULL THEN 'NOT_DETECTED'
    WHEN s.SENSITIVITY_CLASSIFICATION IS NULL THEN 'FALSE_POSITIVE'
    ELSE 'MISMATCH'
  END as accuracy_status,
  d.CONFIDENCE_SCORE,
  CASE
    WHEN d.DETECTED_CLASSIFICATION = s.SENSITIVITY_CLASSIFICATION THEN 'PASS'
    WHEN d.DETECTED_CLASSIFICATION IS NULL AND s.SENSITIVITY_CLASSIFICATION IN ('PII', 'ACCOUNT_DETAILS') THEN 'FAIL_MISSED'
    WHEN d.DETECTED_CLASSIFICATION IN ('PII', 'ACCOUNT_DETAILS') AND s.SENSITIVITY_CLASSIFICATION NOT IN ('PII', 'ACCOUNT_DETAILS') THEN 'FAIL_FALSE_POSITIVE'
    ELSE 'FAIL_MISMATCH'
  END as test_result
FROM DATA_DISCOVERY_RESULTS d
FULL OUTER JOIN DATA_DICTIONARY s 
  ON d.TABLE_NAME = s.TABLE_NAME 
  AND d.COLUMN_NAME = s.COLUMN_NAME
WHERE d.TABLE_NAME IS NOT NULL OR s.TABLE_NAME IS NOT NULL;

-- Show accuracy metrics
SELECT 'Classification Accuracy Report:' as section;

SELECT 'Overall Results:' as metric;
SELECT 
  test_result,
  COUNT(*) as count
FROM CLASSIFICATION_ACCURACY_VIEW
GROUP BY test_result
ORDER BY count DESC;

SELECT 'Detailed Comparison (Mismatches Only):' as section;
SELECT 
  TABLE_NAME,
  COLUMN_NAME,
  detected_class,
  sealed_class,
  accuracy_status,
  CONFIDENCE_SCORE
FROM CLASSIFICATION_ACCURACY_VIEW
WHERE accuracy_status != 'MATCH'
ORDER BY TABLE_NAME, COLUMN_NAME;

SELECT 'PAN Detection Summary:' as section;
SELECT 
  COUNT(*) as total_pans_found,
  SUM(CASE WHEN LUHN_VALID THEN 1 ELSE 0 END) as valid_luhn_pans,
  COUNT(DISTINCT TABLE_NAME) as affected_tables
FROM PAN_DETECTION_RESULTS;

SELECT '✓ Classification accuracy comparison complete' as status;
