-- classification/create_approval_workflow.sql
-- Steward review and approval workflow

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

-- ============================================
-- POPULATE STEWARD APPROVAL QUEUE
-- ============================================
INSERT INTO STEWARD_APPROVAL_QUEUE (
  APPROVAL_ID, DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, COLUMN_NAME,
  DETECTED_CLASSIFICATION, SEALED_CLASSIFICATION, MATCH_STATUS,
  APPROVAL_STATUS, NOTES
)
SELECT 
  'APV_' || ROW_NUMBER() OVER (ORDER BY d.TABLE_NAME, d.COLUMN_NAME),
  'RAW',
  'PUBLIC',
  d.TABLE_NAME,
  d.COLUMN_NAME,
  d.DETECTED_CLASSIFICATION,
  s.SENSITIVITY_CLASSIFICATION,
  CASE 
    WHEN d.DETECTED_CLASSIFICATION = s.SENSITIVITY_CLASSIFICATION THEN 'MATCH'
    WHEN d.DETECTED_CLASSIFICATION IS NULL THEN 'NOT_DETECTED'
    ELSE 'NEEDS_REVIEW'
  END,
  'PENDING',
  'Awaiting steward approval'
FROM DATA_DISCOVERY_RESULTS d
FULL OUTER JOIN DATA_DICTIONARY s 
  ON d.TABLE_NAME = s.TABLE_NAME 
  AND d.COLUMN_NAME = s.COLUMN_NAME
WHERE d.TABLE_NAME IS NOT NULL OR s.TABLE_NAME IS NOT NULL;

-- Simulate steward approval (AUTO-APPROVE matches)
UPDATE STEWARD_APPROVAL_QUEUE
SET APPROVAL_STATUS = 'APPROVED',
    APPROVED_BY = 'DATA_STEWARD',
    APPROVAL_TIMESTAMP = CURRENT_TIMESTAMP(),
    NOTES = 'Auto-approved: Detection matches sealed baseline'
WHERE MATCH_STATUS = 'MATCH';

-- Flag mismatches for manual review
UPDATE STEWARD_APPROVAL_QUEUE
SET APPROVAL_STATUS = 'PENDING_REVIEW',
    NOTES = 'Flagged for manual steward review: Classification mismatch'
WHERE MATCH_STATUS != 'MATCH' AND APPROVAL_STATUS = 'PENDING';

-- Show approval queue
SELECT 'Steward Approval Queue:' as status;
SELECT 
  APPROVAL_STATUS,
  COUNT(*) as count
FROM STEWARD_APPROVAL_QUEUE
GROUP BY APPROVAL_STATUS;

SELECT 'Pending Review Items:' as status;
SELECT 
  TABLE_NAME,
  COLUMN_NAME,
  DETECTED_CLASSIFICATION,
  SEALED_CLASSIFICATION,
  NOTES
FROM STEWARD_APPROVAL_QUEUE
WHERE APPROVAL_STATUS = 'PENDING_REVIEW'
ORDER BY TABLE_NAME, COLUMN_NAME;

SELECT 'Approved Items:' as status;
SELECT 
  TABLE_NAME,
  COLUMN_NAME,
  MATCH_STATUS,
  APPROVED_BY
FROM STEWARD_APPROVAL_QUEUE
WHERE APPROVAL_STATUS = 'APPROVED'
LIMIT 10;

SELECT '✓ Steward approval workflow initialized' as status;
