-- classification/create_discovery_scan.sql
-- Scan RAW tables using CLASSIFICATION_PROFILES rules (proper governance)

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

-- ============================================
-- PROCEDURE: SCAN_DATA_DISCOVERY (Using Rules)
-- ============================================
CREATE OR REPLACE PROCEDURE SCAN_DATA_DISCOVERY()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
  -- Scan columns by MATCHING AGAINST CLASSIFICATION_PROFILES rules
  INSERT INTO DATA_DISCOVERY_RESULTS (
    DISCOVERY_ID, DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, COLUMN_NAME,
    DETECTED_CLASSIFICATION, CONFIDENCE_SCORE, SAMPLE_VALUES, SCAN_TIMESTAMP
  )
  SELECT 
    'DISCO_' || ROW_NUMBER() OVER (ORDER BY cm.TABLE_NAME, cm.COLUMN_NAME),
    cm.DATABASE_NAME,
    cm.SCHEMA_NAME,
    cm.TABLE_NAME,
    cm.COLUMN_NAME,
    -- JOIN to CLASSIFICATION_PROFILES and apply rules
    COALESCE(cp.CLASSIFICATION, 'PUBLIC') as DETECTED_CLASSIFICATION,
    COALESCE(cp_score.CONFIDENCE, 0.50) as CONFIDENCE_SCORE,
    'Rule: ' || COALESCE(cp.PROFILE_NAME, 'Default') as SAMPLE_VALUES,
    CURRENT_TIMESTAMP()
  FROM GOVERNANCE.CATALOG.COLUMN_METADATA cm
  -- LEFT JOIN to find matching rules
  LEFT JOIN GOVERNANCE.CATALOG.CLASSIFICATION_PROFILES cp
    ON cm.COLUMN_NAME ILIKE '%' || cp.PROFILE_NAME || '%'
  -- Score confidence based on match
  LEFT JOIN (
    SELECT PROFILE_NAME, SENSITIVITY_LEVEL,
      CASE 
        WHEN SENSITIVITY_LEVEL = 'CRITICAL' THEN 0.95
        WHEN SENSITIVITY_LEVEL = 'HIGH' THEN 0.85
        ELSE 0.70
      END as CONFIDENCE
    FROM GOVERNANCE.CATALOG.CLASSIFICATION_PROFILES
  ) cp_score ON cp.PROFILE_NAME = cp_score.PROFILE_NAME
  WHERE cm.DATABASE_NAME = 'RAW' 
    AND cm.SCHEMA_NAME = 'PUBLIC';

  RETURN 'Data discovery scan complete - using CLASSIFICATION_PROFILES rules';
END;
$$;

-- Run discovery scan
CALL SCAN_DATA_DISCOVERY();

-- View results with rule traceability
SELECT 'Data Discovery Results (Rule-Based):' as status;
SELECT COUNT(*) as columns_scanned FROM DATA_DISCOVERY_RESULTS;

SELECT 'Detected Classifications with Rules Applied:' as status;
SELECT 
  TABLE_NAME, 
  COLUMN_NAME, 
  DETECTED_CLASSIFICATION,
  SAMPLE_VALUES as rule_applied,
  CONFIDENCE_SCORE
FROM DATA_DISCOVERY_RESULTS
WHERE DETECTED_CLASSIFICATION NOT IN ('PUBLIC')
ORDER BY TABLE_NAME, COLUMN_NAME;

SELECT 'Rule Audit Trail (Which rules matched which columns):' as status;
SELECT 
  cm.TABLE_NAME,
  cm.COLUMN_NAME,
  cp.PROFILE_NAME as matched_rule,
  cp.CLASSIFICATION as classification_applied,
  cp.SENSITIVITY_LEVEL
FROM GOVERNANCE.CATALOG.COLUMN_METADATA cm
LEFT JOIN GOVERNANCE.CATALOG.CLASSIFICATION_PROFILES cp
  ON cm.COLUMN_NAME ILIKE '%' || cp.PROFILE_NAME || '%'
WHERE cm.DATABASE_NAME = 'RAW' 
  AND cm.SCHEMA_NAME = 'PUBLIC'
  AND cp.CLASSIFICATION IS NOT NULL
ORDER BY cm.TABLE_NAME, cm.COLUMN_NAME;

SELECT '✓ Data discovery scan complete - Rules enforced' as status;
