-- classification/create_classification_tables.sql
-- Create tables for classification management

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

-- ============================================
-- 1. CLASSIFICATION PROFILES (Pattern rules)
-- ============================================
CREATE TABLE IF NOT EXISTS CLASSIFICATION_PROFILES (
  PROFILE_ID INTEGER,
  PROFILE_NAME VARCHAR NOT NULL,
  PATTERN_RULE VARCHAR,
  CLASSIFICATION VARCHAR,
  SENSITIVITY_LEVEL VARCHAR,
  DETECTION_METHOD VARCHAR,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (PROFILE_ID)
);

-- ============================================
-- 2. DATA DISCOVERY RESULTS (Scan findings)
-- ============================================
CREATE TABLE IF NOT EXISTS DATA_DISCOVERY_RESULTS (
  DISCOVERY_ID VARCHAR,
  DATABASE_NAME VARCHAR,
  SCHEMA_NAME VARCHAR,
  TABLE_NAME VARCHAR,
  COLUMN_NAME VARCHAR,
  DETECTED_CLASSIFICATION VARCHAR,
  CONFIDENCE_SCORE DECIMAL(3,2),
  SAMPLE_VALUES VARCHAR,
  SCAN_TIMESTAMP TIMESTAMP_NTZ,
  PRIMARY KEY (DISCOVERY_ID)
);

-- ============================================
-- 3. STEWARD APPROVAL QUEUE
-- ============================================
CREATE TABLE IF NOT EXISTS STEWARD_APPROVAL_QUEUE (
  APPROVAL_ID VARCHAR,
  DATABASE_NAME VARCHAR,
  SCHEMA_NAME VARCHAR,
  TABLE_NAME VARCHAR,
  COLUMN_NAME VARCHAR,
  DETECTED_CLASSIFICATION VARCHAR,
  SEALED_CLASSIFICATION VARCHAR,
  MATCH_STATUS VARCHAR,
  APPROVED_BY VARCHAR,
  APPROVAL_TIMESTAMP TIMESTAMP_NTZ,
  APPROVAL_STATUS VARCHAR,
  NOTES VARCHAR,
  PRIMARY KEY (APPROVAL_ID)
);

-- ============================================
-- 4. CLASSIFICATION EXCEPTIONS (Mismatches)
-- ============================================
CREATE TABLE IF NOT EXISTS CLASSIFICATION_EXCEPTIONS (
  EXCEPTION_ID VARCHAR,
  TABLE_NAME VARCHAR,
  COLUMN_NAME VARCHAR,
  SEALED_CLASSIFICATION VARCHAR,
  DETECTED_CLASSIFICATION VARCHAR,
  EXCEPTION_TYPE VARCHAR,
  SEVERITY VARCHAR,
  DESCRIPTION VARCHAR,
  LOGGED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (EXCEPTION_ID)
);

-- ============================================
-- 5. PAN DETECTION RESULTS (Card number scans)
-- ============================================
CREATE TABLE IF NOT EXISTS PAN_DETECTION_RESULTS (
  PAN_DETECTION_ID VARCHAR,
  TABLE_NAME VARCHAR,
  COLUMN_NAME VARCHAR,
  SAMPLE_VALUE VARCHAR,
  DETECTED_PAN VARCHAR,
  LUHN_VALID BOOLEAN,
  CONFIDENCE_SCORE DECIMAL(3,2),
  SCAN_TIMESTAMP TIMESTAMP_NTZ,
  PRIMARY KEY (PAN_DETECTION_ID)
);

SELECT 'Classification infrastructure created' as status;
