-- classification/create_discovery_scan.sql
-- Scan RAW tables for sensitive patterns

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

-- ============================================
-- PROCEDURE: SCAN_DATA_DISCOVERY
-- ============================================
CREATE OR REPLACE PROCEDURE SCAN_DATA_DISCOVERY()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
  -- Scan by column names matching patterns
  INSERT INTO DATA_DISCOVERY_RESULTS (
    DISCOVERY_ID, DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, COLUMN_NAME,
    DETECTED_CLASSIFICATION, CONFIDENCE_SCORE, SAMPLE_VALUES, SCAN_TIMESTAMP
  )
  SELECT 
    'DISCO_' || ROW_NUMBER() OVER (ORDER BY TABLE_NAME, COLUMN_NAME),
    'RAW',
    'PUBLIC',
    TABLE_NAME,
    COLUMN_NAME,
    CASE 
      WHEN COLUMN_NAME ILIKE '%EMAIL%' THEN 'PII'
      WHEN COLUMN_NAME ILIKE '%PHONE%' OR COLUMN_NAME ILIKE '%MOBILE%' THEN 'PII'
      WHEN COLUMN_NAME ILIKE '%PASSWORD%' OR COLUMN_NAME ILIKE '%SECRET%' THEN 'SENSITIVE'
      WHEN COLUMN_NAME ILIKE '%ACCOUNT_NUMBER%' OR COLUMN_NAME ILIKE '%CARD%' THEN 'ACCOUNT_DETAILS'
      WHEN COLUMN_NAME ILIKE '%TAX_ID%' OR COLUMN_NAME ILIKE '%SSN%' THEN 'PII'
      WHEN COLUMN_NAME ILIKE '%DOB%' OR COLUMN_NAME ILIKE '%DATE_OF_BIRTH%' THEN 'PII'
      WHEN COLUMN_NAME = 'LOAN_MEMO' THEN 'POTENTIALLY_SENSITIVE'
      ELSE 'PUBLIC'
    END as DETECTED_CLASSIFICATION,
    CASE 
      WHEN COLUMN_NAME ILIKE '%EMAIL%' THEN 0.95
      WHEN COLUMN_NAME ILIKE '%PHONE%' THEN 0.90
      WHEN COLUMN_NAME ILIKE '%PASSWORD%' THEN 1.00
      WHEN COLUMN_NAME = 'LOAN_MEMO' THEN 0.70
      ELSE 0.50
    END as CONFIDENCE_SCORE,
    'Sample scan (column name matching)' as SAMPLE_VALUES,
    CURRENT_TIMESTAMP()
  FROM GOVERNANCE.CATALOG.COLUMN_METADATA
  WHERE DATABASE_NAME = 'RAW' 
    AND SCHEMA_NAME = 'PUBLIC';

  RETURN 'Data discovery scan complete';
END;
$$;

-- Run discovery scan
CALL SCAN_DATA_DISCOVERY();

-- View results
SELECT 'Data Discovery Results:' as status;
SELECT COUNT(*) as columns_scanned FROM DATA_DISCOVERY_RESULTS;

SELECT 'Detected Sensitive Columns:' as status;
SELECT TABLE_NAME, COLUMN_NAME, DETECTED_CLASSIFICATION, CONFIDENCE_SCORE
FROM DATA_DISCOVERY_RESULTS
WHERE DETECTED_CLASSIFICATION NOT IN ('PUBLIC')
ORDER BY TABLE_NAME, COLUMN_NAME;

SELECT '✓ Data discovery scan complete' as status;
