-- Fix: Reload profiles with names that match actual column names

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

-- DELETE old profiles
DELETE FROM CLASSIFICATION_PROFILES;

-- RELOAD with SIMPLE names that match columns
INSERT INTO CLASSIFICATION_PROFILES (PROFILE_ID, PROFILE_NAME, PATTERN_RULE, CLASSIFICATION, SENSITIVITY_LEVEL, DETECTION_METHOD)
VALUES
(1, 'EMAIL', '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$', 'PII', 'HIGH', 'COLUMN_NAME_MATCH'),
(2, 'PHONE', '^\d{3}-\d{3}-\d{4}$', 'PII', 'HIGH', 'COLUMN_NAME_MATCH'),
(3, 'MOBILE', '^\d{3}-\d{3}-\d{4}$', 'PII', 'HIGH', 'COLUMN_NAME_MATCH'),
(4, 'TAX_ID', '^\d{3}-\d{2}-\d{4}$', 'PII', 'CRITICAL', 'COLUMN_NAME_MATCH'),
(5, 'ACCOUNT_NUMBER', '^\d{10}$', 'ACCOUNT_DETAILS', 'CRITICAL', 'FORMAT_MATCH'),
(6, 'DATE_OF_BIRTH', '^\d{4}-\d{2}-\d{2}$', 'PII', 'HIGH', 'FORMAT_MATCH'),
(7, 'PASSWORD', 'PASSWORD|PASSWD', 'SENSITIVE', 'CRITICAL', 'COLUMN_NAME_MATCH'),
(8, 'SECRET', 'SECRET|API_KEY', 'SENSITIVE', 'CRITICAL', 'COLUMN_NAME_MATCH'),
(9, 'MEMO', 'MEMO|NOTE|COMMENT', 'POTENTIALLY_SENSITIVE', 'MEDIUM', 'COLUMN_NAME_MATCH'),
(10, 'PAN', 'CARD|PAN|PAYMENT', 'ACCOUNT_DETAILS', 'CRITICAL', 'COLUMN_NAME_MATCH');

SELECT 'Reloaded profiles:' as status;
SELECT * FROM CLASSIFICATION_PROFILES;

SELECT '✓ Classification profiles reloaded with matching names' as status;
