-- protection/01_permissions.sql
-- One-time security grants. Run the account-level APPLY grants as an
-- account administrator, then run the remaining object grants as a role
-- permitted to grant access in this assessment.

-- Required once for DATA_OWNER to bind policies to the CLASSIFICATION tag
-- and to attach the row access policy to owned tables.
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE DATA_OWNER;
GRANT APPLY ROW ACCESS POLICY ON ACCOUNT TO ROLE DATA_OWNER;
GRANT APPLY TAG ON ACCOUNT TO ROLE DATA_OWNER;

-- Required by SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES_WITH_LINEAGE, which the
-- live sensitive-policy inventory uses to include propagated tags.
GRANT DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER TO ROLE DATA_OWNER;

-- DATA_STEWARD and DEPOSITS_ANALYST need query access to the approved-tag
-- staging objects for the role-behavior validation. Tag policies enforce
-- partial and masked output respectively.
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE DATA_STEWARD;
GRANT USAGE ON DATABASE ANALYTICS TO ROLE DATA_STEWARD;
GRANT USAGE ON SCHEMA ANALYTICS.STAGING TO ROLE DATA_STEWARD;
GRANT SELECT ON TABLE ANALYTICS.STAGING.STG_CUSTOMER TO ROLE DATA_STEWARD;
GRANT SELECT ON TABLE ANALYTICS.STAGING.STG_LOAN TO ROLE DATA_STEWARD;

GRANT USAGE ON DATABASE ANALYTICS TO ROLE DEPOSITS_ANALYST;
GRANT USAGE ON SCHEMA ANALYTICS.STAGING TO ROLE DEPOSITS_ANALYST;
GRANT SELECT ON TABLE ANALYTICS.STAGING.STG_CUSTOMER TO ROLE DEPOSITS_ANALYST;
GRANT SELECT ON TABLE ANALYTICS.STAGING.STG_LOAN TO ROLE DEPOSITS_ANALYST;

-- BRANCH_HUDSON is the constrained role used to prove row access on both
-- a RAW table and the certified deposits mart.
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE BRANCH_HUDSON;
GRANT USAGE ON DATABASE RAW TO ROLE BRANCH_HUDSON;
GRANT USAGE ON SCHEMA RAW.PUBLIC TO ROLE BRANCH_HUDSON;
GRANT SELECT ON TABLE RAW.PUBLIC.ACCOUNT TO ROLE BRANCH_HUDSON;
GRANT USAGE ON DATABASE ANALYTICS TO ROLE BRANCH_HUDSON;
GRANT USAGE ON SCHEMA ANALYTICS.MARTS TO ROLE BRANCH_HUDSON;
GRANT SELECT ON TABLE ANALYTICS.MARTS.MART_DEPOSITS TO ROLE BRANCH_HUDSON;
