-- protection/02_create_tag_based_masking_policies.sql
-- The policies are attached to a tag in the next step; never to a column.

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE OR REPLACE MASKING POLICY CLASSIFICATION_MASK_VARCHAR
AS (VAL VARCHAR) RETURNS VARCHAR ->
  CASE
    WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('GOVERNANCE.CATALOG.CLASSIFICATION')
         NOT IN ('PII', 'ACCOUNT_DETAILS', 'SENSITIVE') THEN VAL
    WHEN CURRENT_ROLE() = 'DATA_OWNER' THEN VAL
    WHEN CURRENT_ROLE() = 'DATA_STEWARD' THEN
      CASE
        WHEN VAL IS NULL THEN NULL
        WHEN LENGTH(VAL) <= 4 THEN '****'
        ELSE LEFT(VAL, 2) || REPEAT('*', LENGTH(VAL) - 4) || RIGHT(VAL, 2)
      END
    ELSE '***MASKED***'
  END;

CREATE OR REPLACE MASKING POLICY CLASSIFICATION_MASK_DATE
AS (VAL DATE) RETURNS DATE ->
  CASE
    WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('GOVERNANCE.CATALOG.CLASSIFICATION')
         NOT IN ('PII', 'ACCOUNT_DETAILS', 'SENSITIVE') THEN VAL
    WHEN CURRENT_ROLE() = 'DATA_OWNER' THEN VAL
    WHEN CURRENT_ROLE() = 'DATA_STEWARD' THEN
      IFF(VAL IS NULL, NULL, DATE_FROM_PARTS(YEAR(VAL), 1, 1))
    ELSE NULL
  END;

-- Included for approved account/PAN values that are represented numerically.
CREATE OR REPLACE MASKING POLICY CLASSIFICATION_MASK_NUMBER
AS (VAL NUMBER) RETURNS NUMBER ->
  CASE
    WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('GOVERNANCE.CATALOG.CLASSIFICATION')
         NOT IN ('PII', 'ACCOUNT_DETAILS', 'SENSITIVE') THEN VAL
    WHEN CURRENT_ROLE() = 'DATA_OWNER' THEN VAL
    WHEN CURRENT_ROLE() = 'DATA_STEWARD' THEN FLOOR(VAL / 10000) * 10000
    ELSE NULL
  END;
