-- protection/04_create_branch_entitlements.sql

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE TABLE IF NOT EXISTS BRANCH_ENTITLEMENTS (
  ROLE_NAME VARCHAR NOT NULL,
  BRANCH_CODE VARCHAR NOT NULL,
  GRANTED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  GRANTED_BY VARCHAR NOT NULL DEFAULT CURRENT_USER(),
  CONSTRAINT BRANCH_ENTITLEMENTS_PK PRIMARY KEY (ROLE_NAME, BRANCH_CODE)
);

-- '*' is an explicit all-branch entitlement for the assessment roles.
MERGE INTO BRANCH_ENTITLEMENTS AS TARGET
USING (
  SELECT COLUMN1 AS ROLE_NAME, COLUMN2 AS BRANCH_CODE
  FROM VALUES
    ('DATA_OWNER', '*'),
    ('DATA_STEWARD', '*'),
    ('DEPOSITS_ANALYST', '*'),
    ('BRANCH_HUDSON', 'BR_01')
) AS SOURCE
ON TARGET.ROLE_NAME = SOURCE.ROLE_NAME
AND TARGET.BRANCH_CODE = SOURCE.BRANCH_CODE
WHEN NOT MATCHED THEN INSERT (ROLE_NAME, BRANCH_CODE)
VALUES (SOURCE.ROLE_NAME, SOURCE.BRANCH_CODE);
