-- protection/05_create_row_access_policy.sql

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE OR REPLACE ROW ACCESS POLICY BRANCH_ENTITLEMENT_POLICY
AS (P_BRANCH_CODE VARCHAR) RETURNS BOOLEAN ->
    EXISTS (
        SELECT 1
        FROM GOVERNANCE.CATALOG.BRANCH_ENTITLEMENTS AS E
        WHERE IS_ROLE_IN_SESSION(E.ROLE_NAME)
          AND (E.BRANCH_CODE = P_BRANCH_CODE OR E.BRANCH_CODE = '*')
    );
