-- protection/07_validate_masking_by_role.sql
-- Displays actual tag-policy metadata and live policy output; it does not
-- manufacture PASS/FAIL evidence.

USE ROLE DATA_OWNER;
SELECT POLICY_DB, POLICY_SCHEMA, POLICY_NAME, POLICY_KIND, POLICY_STATUS,
       REF_ENTITY_NAME, REF_ENTITY_DOMAIN, REF_COLUMN_NAME,
       TAG_DATABASE, TAG_SCHEMA, TAG_NAME
FROM TABLE(GOVERNANCE.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'GOVERNANCE.CATALOG.CLASSIFICATION',
  REF_ENTITY_DOMAIN => 'TAG'
))
WHERE POLICY_KIND = 'MASKING_POLICY'
ORDER BY POLICY_NAME;

USE ROLE DATA_OWNER;
SELECT TAX_ID, DATE_OF_BIRTH, EMAIL, PHONE
FROM ANALYTICS.STAGING.STG_CUSTOMER
WHERE TAX_ID IS NOT NULL OR DATE_OF_BIRTH IS NOT NULL OR EMAIL IS NOT NULL OR PHONE IS NOT NULL
LIMIT 5;
SELECT LOAN_MEMO FROM ANALYTICS.STAGING.STG_LOAN WHERE LOAN_MEMO IS NOT NULL LIMIT 5;

USE ROLE DATA_STEWARD;
SELECT TAX_ID, DATE_OF_BIRTH, EMAIL, PHONE
FROM ANALYTICS.STAGING.STG_CUSTOMER
WHERE TAX_ID IS NOT NULL OR DATE_OF_BIRTH IS NOT NULL OR EMAIL IS NOT NULL OR PHONE IS NOT NULL
LIMIT 5;
SELECT LOAN_MEMO FROM ANALYTICS.STAGING.STG_LOAN WHERE LOAN_MEMO IS NOT NULL LIMIT 5;

USE ROLE DEPOSITS_ANALYST;
SELECT TAX_ID, DATE_OF_BIRTH, EMAIL, PHONE
FROM ANALYTICS.STAGING.STG_CUSTOMER
WHERE TAX_ID IS NOT NULL OR DATE_OF_BIRTH IS NOT NULL OR EMAIL IS NOT NULL OR PHONE IS NOT NULL
LIMIT 5;
SELECT LOAN_MEMO FROM ANALYTICS.STAGING.STG_LOAN WHERE LOAN_MEMO IS NOT NULL LIMIT 5;
