-- protection/08_validate_branch_access.sql
-- Displays the real row-policy references and row distribution for each
-- accessible target. BRANCH_HUDSON should return BR_01 only.

USE ROLE DATA_OWNER;
SELECT POLICY_DB, POLICY_SCHEMA, POLICY_NAME, POLICY_KIND, POLICY_STATUS,
       REF_ENTITY_NAME, REF_ENTITY_DOMAIN
FROM TABLE(GOVERNANCE.INFORMATION_SCHEMA.POLICY_REFERENCES(
  POLICY_NAME => 'GOVERNANCE.CATALOG.BRANCH_ENTITLEMENT_POLICY'
))
WHERE REF_ENTITY_NAME IN ('RAW.PUBLIC.ACCOUNT', 'ANALYTICS.MARTS.MART_DEPOSITS')
ORDER BY REF_ENTITY_NAME;

USE ROLE DATA_OWNER;
SELECT 'RAW.PUBLIC.ACCOUNT' AS OBJECT_NAME, BRANCH_CODE, COUNT(*) AS ROW_COUNT
FROM RAW.PUBLIC.ACCOUNT GROUP BY BRANCH_CODE ORDER BY BRANCH_CODE;
SELECT 'ANALYTICS.MARTS.MART_DEPOSITS' AS OBJECT_NAME, BRANCH_CODE, COUNT(*) AS ROW_COUNT
FROM ANALYTICS.MARTS.MART_DEPOSITS GROUP BY BRANCH_CODE ORDER BY BRANCH_CODE;

USE ROLE BRANCH_HUDSON;
SELECT 'RAW.PUBLIC.ACCOUNT' AS OBJECT_NAME, BRANCH_CODE, COUNT(*) AS ROW_COUNT
FROM RAW.PUBLIC.ACCOUNT GROUP BY BRANCH_CODE ORDER BY BRANCH_CODE;
SELECT 'ANALYTICS.MARTS.MART_DEPOSITS' AS OBJECT_NAME, BRANCH_CODE, COUNT(*) AS ROW_COUNT
FROM ANALYTICS.MARTS.MART_DEPOSITS GROUP BY BRANCH_CODE ORDER BY BRANCH_CODE;
