-- protection/09_sensitive_policy_gap_report.sql
-- Returns a row only for a live sensitive CLASSIFICATION tag whose matching
-- tag-based masking-policy binding is missing. The Snowflake tag-reference
-- inventory includes propagated tags; review records are provenance only.

USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE OR REPLACE VIEW SENSITIVE_POLICY_GAPS AS
WITH live_sensitive_tags AS (
  SELECT OBJECT_DATABASE AS DATABASE_NAME,
         OBJECT_SCHEMA AS SCHEMA_NAME,
         OBJECT_NAME AS TABLE_NAME,
         COLUMN_NAME,
         TAG_VALUE AS CLASSIFICATION_TAG_VALUE,
         APPLY_METHOD
  FROM TABLE(SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES_WITH_LINEAGE(
    'GOVERNANCE.CATALOG.CLASSIFICATION'
  ))
  WHERE DOMAIN = 'COLUMN'
    AND OBJECT_DELETED IS NULL
    AND TAG_VALUE IN ('PII', 'ACCOUNT_DETAILS', 'SENSITIVE')
),
current_columns AS (
  SELECT 'RAW' AS DATABASE_NAME, TABLE_SCHEMA AS SCHEMA_NAME, TABLE_NAME,
         COLUMN_NAME, DATA_TYPE
  FROM RAW.INFORMATION_SCHEMA.COLUMNS
  UNION ALL
  SELECT 'ANALYTICS', TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE
  FROM ANALYTICS.INFORMATION_SCHEMA.COLUMNS
  UNION ALL
  SELECT 'GOVERNANCE', TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE
  FROM GOVERNANCE.INFORMATION_SCHEMA.COLUMNS
),
expected_coverage AS (
  SELECT T.DATABASE_NAME, T.SCHEMA_NAME, T.TABLE_NAME, T.COLUMN_NAME,
         T.CLASSIFICATION_TAG_VALUE, T.APPLY_METHOD, M.DATA_TYPE,
         CASE
           WHEN M.DATA_TYPE IN ('TEXT', 'VARCHAR', 'CHAR', 'CHARACTER')
             THEN 'CLASSIFICATION_MASK_VARCHAR'
           WHEN M.DATA_TYPE = 'DATE' THEN 'CLASSIFICATION_MASK_DATE'
           WHEN M.DATA_TYPE IN ('NUMBER', 'DECIMAL', 'NUMERIC', 'INT', 'INTEGER', 'BIGINT', 'SMALLINT')
             THEN 'CLASSIFICATION_MASK_NUMBER'
           ELSE NULL
         END AS REQUIRED_POLICY
  FROM live_sensitive_tags AS T
  LEFT JOIN current_columns AS M
    ON M.DATABASE_NAME = T.DATABASE_NAME
   AND M.SCHEMA_NAME = T.SCHEMA_NAME
   AND M.TABLE_NAME = T.TABLE_NAME
   AND M.COLUMN_NAME = T.COLUMN_NAME
),
tag_policy_bindings AS (
  SELECT UPPER(POLICY_NAME) AS POLICY_NAME
  FROM TABLE(GOVERNANCE.INFORMATION_SCHEMA.POLICY_REFERENCES(
    REF_ENTITY_NAME => 'GOVERNANCE.CATALOG.CLASSIFICATION',
    REF_ENTITY_DOMAIN => 'TAG'
  ))
  WHERE POLICY_KIND = 'MASKING_POLICY'
    AND POLICY_STATUS = 'ACTIVE'
),
approval_provenance AS (
  SELECT DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, COLUMN_NAME,
         REVIEW_ID, REVIEWED_BY, REVIEWED_AT
  FROM GOVERNANCE.CATALOG.CLASSIFICATION_REVIEW_QUEUE
  WHERE REVIEW_STATUS = 'APPROVED'
),
gaps AS (
SELECT E.DATABASE_NAME, E.SCHEMA_NAME, E.TABLE_NAME, E.COLUMN_NAME,
       E.CLASSIFICATION_TAG_VALUE, E.APPLY_METHOD, E.DATA_TYPE,
       E.REQUIRED_POLICY, P.REVIEW_ID, P.REVIEWED_BY, P.REVIEWED_AT,
       CASE
         WHEN E.DATA_TYPE IS NULL THEN 'COLUMN_NOT_FOUND'
         WHEN E.REQUIRED_POLICY IS NULL THEN 'UNSUPPORTED_MASKING_DATA_TYPE'
         WHEN B.POLICY_NAME IS NULL THEN 'TAG_MASKING_POLICY_NOT_ACTIVE'
       END AS GAP_REASON
FROM expected_coverage AS E
LEFT JOIN tag_policy_bindings AS B
  ON B.POLICY_NAME = E.REQUIRED_POLICY
LEFT JOIN approval_provenance AS P
  ON P.DATABASE_NAME = E.DATABASE_NAME
 AND P.SCHEMA_NAME = E.SCHEMA_NAME
 AND P.TABLE_NAME = E.TABLE_NAME
 AND P.COLUMN_NAME = E.COLUMN_NAME
WHERE E.DATA_TYPE IS NULL
   OR E.REQUIRED_POLICY IS NULL
   OR B.POLICY_NAME IS NULL
)
SELECT * FROM gaps
ORDER BY DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, COLUMN_NAME;

SELECT * FROM GOVERNANCE.CATALOG.SENSITIVE_POLICY_GAPS;
