-- Block 3: measured DQ history. Run once before the opted-in dbt test command.
USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE TABLE IF NOT EXISTS DQ_RESULT (
  DQ_RESULT_ID VARCHAR PRIMARY KEY,
  MART_NAME VARCHAR,
  CHECK_DIMENSION VARCHAR,
  CHECK_TYPE VARCHAR,
  TARGET_TABLE VARCHAR,
  TARGET_COLUMN VARCHAR,
  CHECK_RESULT VARCHAR,
  PASSED_ROWS INTEGER,
  FAILED_ROWS INTEGER,
  TOTAL_ROWS INTEGER,
  DETAILS VARCHAR,
  EXECUTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  EXECUTED_BY VARCHAR
);

-- Additive migration preserves existing history. Legacy rows have no invocation
-- ID and are excluded from the assessment evidence views.
ALTER TABLE DQ_RESULT ADD COLUMN IF NOT EXISTS INVOCATION_ID VARCHAR;
ALTER TABLE DQ_RESULT ADD COLUMN IF NOT EXISTS TEST_UNIQUE_ID VARCHAR;
ALTER TABLE DQ_RESULT ADD COLUMN IF NOT EXISTS DBT_STATUS VARCHAR;
ALTER TABLE DQ_RESULT ADD COLUMN IF NOT EXISTS FAILURE_UNIT VARCHAR;
ALTER TABLE DQ_RESULT ADD COLUMN IF NOT EXISTS SNAPSHOT_DATE DATE;
ALTER TABLE DQ_RESULT ADD COLUMN IF NOT EXISTS FAILURE_RELATION VARCHAR;

-- FAILED_ROWS is the actual dbt failure-record count, interpreted with
-- FAILURE_UNIT. PASSED_ROWS/TOTAL_ROWS remain NULL for new results: there is
-- no universal account-row denominator for these six different measurements.

-- Retire previously deployed procedures that unconditionally inserted PASS.
DROP PROCEDURE IF EXISTS CHECK_COMPLETENESS(VARCHAR, VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS CHECK_UNIQUENESS(VARCHAR, VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS CHECK_VALIDITY(VARCHAR, VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS CHECK_CONSISTENCY(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS CHECK_TIMELINESS(VARCHAR, VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS CHECK_ACCURACY(VARCHAR, VARCHAR, VARCHAR);
