-- Only invocation-scoped measured records qualify as assessment evidence.
USE ROLE DATA_OWNER;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE OR REPLACE VIEW EVIDENCE_DQ_SUMMARY AS
SELECT
  INVOCATION_ID,
  MART_NAME,
  COUNT(*) AS checks_recorded,
  COUNT(DISTINCT CHECK_DIMENSION) AS dimensions_recorded,
  SUM(CASE WHEN CHECK_RESULT = 'PASS' THEN 1 ELSE 0 END) AS passed,
  SUM(CASE WHEN CHECK_RESULT = 'FAIL' THEN 1 ELSE 0 END) AS failed,
  SUM(CASE WHEN CHECK_RESULT IN ('ERROR', 'NOT_EXECUTED', 'BLOCKED')
           OR CHECK_RESULT IS NULL THEN 1 ELSE 0 END) AS unresolved,
  CASE
    WHEN COUNT(*) <> 6 OR COUNT(DISTINCT CHECK_DIMENSION) <> 6 THEN 'INCOMPLETE'
    WHEN SUM(CASE WHEN CHECK_RESULT = 'PASS' THEN 1 ELSE 0 END) = 6 THEN 'PASS'
    ELSE 'NOT_PASSED'
  END AS assessment_result,
  MAX(EXECUTED_AT) AS executed_at
FROM DQ_RESULT
WHERE INVOCATION_ID IS NOT NULL
GROUP BY INVOCATION_ID, MART_NAME;

-- Show actual rules/units recorded for each execution, rather than static
-- descriptions that claim a procedure validated data without measuring it.
CREATE OR REPLACE VIEW EVIDENCE_DQ_FRAMEWORK AS
SELECT INVOCATION_ID, MART_NAME, CHECK_DIMENSION, CHECK_TYPE,
       TARGET_TABLE, TARGET_COLUMN, FAILURE_UNIT, DBT_STATUS, CHECK_RESULT
FROM DQ_RESULT
WHERE INVOCATION_ID IS NOT NULL;
