USE ROLE SVC_PIPELINE;

-- ------------------------------------------------------------
-- RAW CI workspace
-- Fresh schema owned by SVC_PIPELINE.
-- Individual source tables are zero-copy cloned into it.
-- ------------------------------------------------------------

CREATE OR REPLACE SCHEMA CI.RAW_PUBLIC_CI;

CREATE OR REPLACE TABLE CI.RAW_PUBLIC_CI.CUSTOMER
CLONE RAW.PUBLIC.CUSTOMER;

CREATE OR REPLACE TABLE CI.RAW_PUBLIC_CI.ACCOUNT
CLONE RAW.PUBLIC.ACCOUNT;

CREATE OR REPLACE TABLE CI.RAW_PUBLIC_CI.TRANSACTION
CLONE RAW.PUBLIC.TRANSACTION;

CREATE OR REPLACE TABLE CI.RAW_PUBLIC_CI.LOAN
CLONE RAW.PUBLIC.LOAN;

CREATE OR REPLACE TABLE CI.RAW_PUBLIC_CI.GL_CONTROL
CLONE RAW.PUBLIC.GL_CONTROL;

CREATE OR REPLACE TABLE CI.RAW_PUBLIC_CI.BRANCH
CLONE RAW.PUBLIC.BRANCH;

CREATE OR REPLACE TABLE CI.RAW_PUBLIC_CI.PRODUCT
CLONE RAW.PUBLIC.PRODUCT;




-- ------------------------------------------------------------
-- Empty dbt target schemas owned by SVC_PIPELINE
-- ------------------------------------------------------------

CREATE OR REPLACE SCHEMA CI.ANALYTICS_STAGING_CI;

CREATE OR REPLACE SCHEMA CI.ANALYTICS_MARTS_CI;

CREATE OR REPLACE SCHEMA CI.GOVERNANCE_CATALOG_CI;