USE ROLE SVC_PIPELINE;

DROP SCHEMA IF EXISTS CI.RAW_PUBLIC_CI;
DROP SCHEMA IF EXISTS CI.ANALYTICS_STAGING_CI;
DROP SCHEMA IF EXISTS CI.ANALYTICS_MARTS_CI;
DROP SCHEMA IF EXISTS CI.GOVERNANCE_CATALOG_CI;