USE ROLE SVC_PIPELINE;

-- Ensure staging models were created.
SELECT COUNT(*) AS STG_CUSTOMER_COUNT
FROM CI.ANALYTICS_STAGING_CI.STG_CUSTOMER;

SELECT COUNT(*) AS STG_ACCOUNT_COUNT
FROM CI.ANALYTICS_STAGING_CI.STG_ACCOUNT;

-- Ensure mart exists and has rows.
SELECT COUNT(*) AS MART_DEPOSITS_COUNT
FROM CI.ANALYTICS_MARTS_CI.MART_DEPOSITS;

-- Ensure transaction/account relationship is intact.
SELECT COUNT(*) AS ORPHAN_TRANSACTION_COUNT
FROM CI.RAW_PUBLIC_CI.TRANSACTION t
LEFT JOIN CI.RAW_PUBLIC_CI.ACCOUNT a
  ON t.ACCOUNT_ID = a.ACCOUNT_ID
WHERE a.ACCOUNT_ID IS NULL;