-- setup/03_grant_permissions.sql
-- Run as ACCOUNTADMIN

USE ROLE ACCOUNTADMIN;

-- ========================================
-- 4. DETAILED PERMISSIONS
-- ========================================

-- DATA_OWNER: Full control
GRANT CREATE TABLE ON SCHEMA RAW.PUBLIC TO ROLE DATA_OWNER;
GRANT CREATE TABLE ON SCHEMA ANALYTICS.STAGING TO ROLE DATA_OWNER;
GRANT CREATE TABLE ON SCHEMA ANALYTICS.MARTS TO ROLE DATA_OWNER;
GRANT CREATE PROCEDURE ON SCHEMA GOVERNANCE.APPROVALS TO ROLE DATA_OWNER;
GRANT CREATE MASKING POLICY ON SCHEMA GOVERNANCE.TAGS TO ROLE DATA_OWNER;

-- SVC_PIPELINE: Can execute procedures, refresh tables
GRANT USAGE ON DATABASE RAW TO ROLE SVC_PIPELINE;
GRANT USAGE ON SCHEMA RAW.PUBLIC TO ROLE SVC_PIPELINE;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW.PUBLIC TO ROLE SVC_PIPELINE;

GRANT USAGE ON DATABASE GOVERNANCE TO ROLE SVC_PIPELINE;
GRANT USAGE ON SCHEMA GOVERNANCE.QUALITY TO ROLE SVC_PIPELINE;
GRANT CREATE TABLE ON SCHEMA GOVERNANCE.QUALITY TO ROLE SVC_PIPELINE;

-- DEPOSITS_ANALYST: Read marts only, SELECT is enough
-- (masking policies applied at query time)

SHOW GRANTS TO ROLE DATA_OWNER;
SHOW GRANTS TO ROLE DEPOSITS_ANALYST;
