-- setup/03_grant_permissions.sql
-- Run as ACCOUNTADMIN

USE ROLE ACCOUNTADMIN;

-- ========================================
-- 1. DATA_OWNER: Full control
-- ========================================

GRANT CREATE TABLE ON SCHEMA RAW.PUBLIC TO ROLE DATA_OWNER;
GRANT CREATE FILE FORMAT ON SCHEMA RAW.PUBLIC TO ROLE DATA_OWNER;
GRANT CREATE PROCEDURE ON SCHEMA RAW.PUBLIC TO ROLE DATA_OWNER;
GRANT USAGE ON SCHEMA RAW.PUBLIC TO ROLE DATA_OWNER;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW.PUBLIC TO ROLE DATA_OWNER;

GRANT CREATE TABLE ON SCHEMA ANALYTICS.STAGING TO ROLE DATA_OWNER;
GRANT CREATE TABLE ON SCHEMA ANALYTICS.MARTS TO ROLE DATA_OWNER;
GRANT CREATE TABLE ON SCHEMA ANALYTICS.INTERMEDIATE TO ROLE DATA_OWNER;
GRANT USAGE ON SCHEMA ANALYTICS.STAGING TO ROLE DATA_OWNER;
GRANT USAGE ON SCHEMA ANALYTICS.MARTS TO ROLE DATA_OWNER;
GRANT USAGE ON SCHEMA ANALYTICS.INTERMEDIATE TO ROLE DATA_OWNER;

GRANT CREATE TABLE ON SCHEMA GOVERNANCE.CATALOG TO ROLE DATA_OWNER;
GRANT CREATE TABLE ON SCHEMA GOVERNANCE.QUALITY TO ROLE DATA_OWNER;
GRANT CREATE TABLE ON SCHEMA GOVERNANCE.APPROVALS TO ROLE DATA_OWNER;
GRANT CREATE PROCEDURE ON SCHEMA GOVERNANCE.APPROVALS TO ROLE DATA_OWNER;
GRANT CREATE MASKING POLICY ON SCHEMA GOVERNANCE.CATALOG TO ROLE DATA_OWNER;
GRANT CREATE ROW ACCESS POLICY ON SCHEMA GOVERNANCE.CATALOG TO ROLE DATA_OWNER;

-- ========================================
-- 2. SVC_PIPELINE: Scheduled task executor
-- ========================================

GRANT USAGE ON DATABASE RAW TO ROLE SVC_PIPELINE;
GRANT USAGE ON SCHEMA RAW.PUBLIC TO ROLE SVC_PIPELINE;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW.PUBLIC TO ROLE SVC_PIPELINE;

GRANT USAGE ON DATABASE GOVERNANCE TO ROLE SVC_PIPELINE;
GRANT USAGE ON SCHEMA GOVERNANCE.QUALITY TO ROLE SVC_PIPELINE;
GRANT CREATE TABLE ON SCHEMA GOVERNANCE.QUALITY TO ROLE SVC_PIPELINE;
GRANT INSERT ON ALL TABLES IN SCHEMA GOVERNANCE.QUALITY TO ROLE SVC_PIPELINE;

--

snow sql -f setup/03_grant_permissions.sql

cat > setup/load_raw.sql << 'EOF'
-- setup/load_raw.sql
-- Load CSV from stage into RAW tables
-- Run as: snow sql -f setup/load_raw.sql

USE ROLE DATA_OWNER;
USE DATABASE RAW;
USE WAREHOUSE TRANSFORM_WH;

-- ============================================
-- CREATE FILE FORMAT
-- ============================================
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null', '')
  EMPTY_FIELD_AS_NULL = TRUE;

-- ============================================
-- 1. CUSTOMER TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS RAW.PUBLIC.CUSTOMER (
  CUSTOMER_ID VARCHAR NOT NULL,
  FIRST_NAME VARCHAR,
  LAST_NAME VARCHAR,
  CUSTOMER_TYPE VARCHAR,
  TAX_ID VARCHAR,  -- SENSITIVE - will be masked
  DATE_OF_BIRTH DATE,  -- SENSITIVE - will be masked
  EMAIL VARCHAR,  -- SENSITIVE - will be masked
  PHONE VARCHAR,  -- SENSITIVE - will be masked
  ADDRESS VARCHAR,
  CREATED_AT TIMESTAMP_NTZ,
  _LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO RAW.PUBLIC.CUSTOMER (
  CUSTOMER_ID, FIRST_NAME, LAST_NAME, CUSTOMER_TYPE, TAX_ID,
  DATE_OF_BIRTH, EMAIL, PHONE, ADDRESS, CREATED_AT
)
FROM @RAW_DATA_STAGE/customers.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

-- ============================================
-- 2. ACCOUNT TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS RAW.PUBLIC.ACCOUNT (
  ACCOUNT_ID VARCHAR NOT NULL,
  CUSTOMER_ID VARCHAR NOT NULL,
  ACCOUNT_TYPE VARCHAR,
  ACCOUNT_NUMBER VARCHAR,  -- SENSITIVE - custom classifier
  BRANCH_CODE VARCHAR,
  BALANCE DECIMAL(15,2),
  STATUS VARCHAR,
  OPENED_DATE DATE,
  CREATED_AT TIMESTAMP_NTZ,
  _LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO RAW.PUBLIC.ACCOUNT (
  ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, ACCOUNT_NUMBER, BRANCH_CODE,
  BALANCE, STATUS, OPENED_DATE, CREATED_AT
)
FROM @RAW_DATA_STAGE/accounts.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

-- ============================================
-- 3. TRANSACTION TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS RAW.PUBLIC.TRANSACTION (
  TRANSACTION_ID VARCHAR NOT NULL,
  ACCOUNT_ID VARCHAR NOT NULL,
  TRANSACTION_TYPE VARCHAR,
  AMOUNT DECIMAL(12,2),
  BUSINESS_DATE DATE,
  MEMO VARCHAR,  -- SENSITIVE: May contain PII in free text
  CREATED_AT TIMESTAMP_NTZ,
  _LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO RAW.PUBLIC.TRANSACTION (
  TRANSACTION_ID, ACCOUNT_ID, TRANSACTION_TYPE, AMOUNT,
  BUSINESS_DATE, MEMO, CREATED_AT
)
FROM @RAW_DATA_STAGE/transactions.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

-- ============================================
-- 4. LOAN TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS RAW.PUBLIC.LOAN (
  LOAN_ID VARCHAR NOT NULL,
  CUSTOMER_ID VARCHAR NOT NULL,
  ACCOUNT_ID VARCHAR,
  LOAN_TYPE VARCHAR,
  PRINCIPAL DECIMAL(15,2),
  INTEREST_RATE DECIMAL(5,2),
  CREDIT_GRADE VARCHAR,
  COLLATERAL_VALUE DECIMAL(15,2),
  LOAN_MEMO VARCHAR,  -- SENSITIVE: May contain hidden card PANs
  STATUS VARCHAR,
  ORIGINATION_DATE DATE,
  _LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO RAW.PUBLIC.LOAN (
  LOAN_ID, CUSTOMER_ID, ACCOUNT_ID, LOAN_TYPE, PRINCIPAL,
  INTEREST_RATE, CREDIT_GRADE, COLLATERAL_VALUE, LOAN_MEMO, STATUS,
  ORIGINATION_DATE
)
FROM @RAW_DATA_STAGE/loans.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

-- ============================================
-- 5. GL_CONTROL TABLE (Reconciliation)
-- ============================================
CREATE TABLE IF NOT EXISTS RAW.PUBLIC.GL_CONTROL (
  GL_CODE VARCHAR NOT NULL,
  ACCOUNT_TYPE VARCHAR,
  CONTROL_TOTAL DECIMAL(15,2),
  RECORD_COUNT INTEGER,
  AS_OF_DATE DATE,
  _LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO RAW.PUBLIC.GL_CONTROL (
  GL_CODE, ACCOUNT_TYPE, CONTROL_TOTAL, RECORD_COUNT, AS_OF_DATE
)
FROM @RAW_DATA_STAGE/gl_control.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

-- ============================================
-- REFERENCE TABLES
-- ============================================
CREATE TABLE IF NOT EXISTS RAW.PUBLIC.BRANCH (
  BRANCH_CODE VARCHAR NOT NULL,
  BRANCH_NAME VARCHAR,
  BRANCH_MANAGER VARCHAR,
  REGION VARCHAR
);

COPY INTO RAW.PUBLIC.BRANCH (
  BRANCH_CODE, BRANCH_NAME, BRANCH_MANAGER, REGION
)
FROM @RAW_DATA_STAGE/branches.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

CREATE TABLE IF NOT EXISTS RAW.PUBLIC.PRODUCT (
  PRODUCT_CODE VARCHAR NOT NULL,
  PRODUCT_NAME VARCHAR,
  ACCOUNT_TYPE VARCHAR,
  TIER VARCHAR
);

COPY INTO RAW.PUBLIC.PRODUCT (
  PRODUCT_CODE, PRODUCT_NAME, ACCOUNT_TYPE, TIER
)
FROM @RAW_DATA_STAGE/products.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

-- ============================================
-- VALIDATION QUERIES
-- ============================================
SELECT '✓ CUSTOMER table loaded' AS status;
SELECT COUNT(*) as customer_count FROM RAW.PUBLIC.CUSTOMER;

SELECT '✓ ACCOUNT table loaded' AS status;
SELECT COUNT(*) as account_count FROM RAW.PUBLIC.ACCOUNT;

SELECT '✓ TRANSACTION table loaded' AS status;
SELECT COUNT(*) as transaction_count FROM RAW.PUBLIC.TRANSACTION;

SELECT '✓ LOAN table loaded' AS status;
SELECT COUNT(*) as loan_count FROM RAW.PUBLIC.LOAN;

SELECT '✓ GL_CONTROL table loaded' AS status;
SELECT * FROM RAW.PUBLIC.GL_CONTROL;

-- Check reconciliation: Sum account balances vs GL control
SELECT 
  'Reconciliation Check' AS check_type,
  SUM(BALANCE) AS total_deposits_from_accounts,
  (SELECT SUM(CONTROL_TOTAL) FROM RAW.PUBLIC.GL_CONTROL) AS gl_control_total,
  ABS(SUM(BALANCE) - (SELECT SUM(CONTROL_TOTAL) FROM RAW.PUBLIC.GL_CONTROL)) AS variance
FROM RAW.PUBLIC.ACCOUNT;

PRINT '✓ Block 0: DATA FOUNDATION COMPLETE';
