-- setup/03_grant_permissions.sql
-- Run as ACCOUNTADMIN

USE ROLE ACCOUNTADMIN;

-- ========================================
-- 1. DATA_OWNER: Full control
-- ========================================

GRANT CREATE TABLE ON SCHEMA RAW.PUBLIC TO ROLE DATA_OWNER;
GRANT CREATE FILE FORMAT ON SCHEMA RAW.PUBLIC TO ROLE DATA_OWNER;
GRANT CREATE PROCEDURE ON SCHEMA RAW.PUBLIC TO ROLE DATA_OWNER;
GRANT USAGE ON SCHEMA RAW.PUBLIC TO ROLE DATA_OWNER;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW.PUBLIC TO ROLE DATA_OWNER;

GRANT CREATE TABLE ON SCHEMA ANALYTICS.STAGING TO ROLE DATA_OWNER;
GRANT CREATE TABLE ON SCHEMA ANALYTICS.MARTS TO ROLE DATA_OWNER;
GRANT CREATE TABLE ON SCHEMA ANALYTICS.INTERMEDIATE TO ROLE DATA_OWNER;
GRANT USAGE ON SCHEMA ANALYTICS.STAGING TO ROLE DATA_OWNER;
GRANT USAGE ON SCHEMA ANALYTICS.MARTS TO ROLE DATA_OWNER;
GRANT USAGE ON SCHEMA ANALYTICS.INTERMEDIATE TO ROLE DATA_OWNER;

GRANT CREATE TABLE ON SCHEMA GOVERNANCE.CATALOG TO ROLE DATA_OWNER;
GRANT CREATE TABLE ON SCHEMA GOVERNANCE.QUALITY TO ROLE DATA_OWNER;
GRANT CREATE TABLE ON SCHEMA GOVERNANCE.APPROVALS TO ROLE DATA_OWNER;
GRANT CREATE PROCEDURE ON SCHEMA GOVERNANCE.APPROVALS TO ROLE DATA_OWNER;
GRANT CREATE MASKING POLICY ON SCHEMA GOVERNANCE.CATALOG TO ROLE DATA_OWNER;
GRANT CREATE ROW ACCESS POLICY ON SCHEMA GOVERNANCE.CATALOG TO ROLE DATA_OWNER;

-- ========================================
-- 2. SVC_PIPELINE: Scheduled task executor
-- ========================================

GRANT USAGE ON DATABASE RAW TO ROLE SVC_PIPELINE;
GRANT USAGE ON SCHEMA RAW.PUBLIC TO ROLE SVC_PIPELINE;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW.PUBLIC TO ROLE SVC_PIPELINE;

GRANT USAGE ON DATABASE GOVERNANCE TO ROLE SVC_PIPELINE;
GRANT USAGE ON SCHEMA GOVERNANCE.QUALITY TO ROLE SVC_PIPELINE;
GRANT CREATE TABLE ON SCHEMA GOVERNANCE.QUALITY TO ROLE SVC_PIPELINE;
GRANT INSERT ON ALL TABLES IN SCHEMA GOVERNANCE.QUALITY TO ROLE SVC_PIPELINE;

-- ========================================
-- 3. DEPOSITS_ANALYST: Read marts only
-- ========================================

GRANT USAGE ON DATABASE ANALYTICS TO ROLE DEPOSITS_ANALYST;
GRANT USAGE ON SCHEMA ANALYTICS.MARTS TO ROLE DEPOSITS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS.MARTS TO ROLE DEPOSITS_ANALYST;

-- ========================================
-- 4. BRANCH_HUDSON: Row-access scoped
-- ========================================

GRANT USAGE ON DATABASE ANALYTICS TO ROLE BRANCH_HUDSON;
GRANT USAGE ON SCHEMA ANALYTICS.MARTS TO ROLE BRANCH_HUDSON;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS.MARTS TO ROLE BRANCH_HUDSON;

SHOW GRANTS TO ROLE DATA_OWNER;
