-- setup/04_ci_bootstrap.sql
-- One-time administrative bootstrap for GitHub Actions CI.
-- This file is NOT executed by the GitHub Actions service user.
-- It prepares a least-privilege CI workspace for SVC_PIPELINE.

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS CI
    COMMENT = 'Ephemeral zero-copy clone workspace for GitHub Actions CI';

GRANT USAGE
ON DATABASE CI
TO ROLE SVC_PIPELINE;

GRANT CREATE SCHEMA
ON DATABASE CI
TO ROLE SVC_PIPELINE;



GRANT USAGE ON DATABASE ANALYTICS TO ROLE SVC_PIPELINE;

GRANT USAGE ON SCHEMA ANALYTICS.STAGING TO ROLE SVC_PIPELINE;
GRANT USAGE ON SCHEMA ANALYTICS.MARTS TO ROLE SVC_PIPELINE;

GRANT USAGE ON DATABASE GOVERNANCE TO ROLE SVC_PIPELINE;
GRANT USAGE ON SCHEMA GOVERNANCE.CATALOG TO ROLE SVC_PIPELINE;
SHOW GRANTS TO ROLE SVC_PIPELINE;