-- setup/load_raw.sql
-- Canonical RAW schema and truncate/reload, invoked by setup/load_data.py.
-- Direct execution requires all current CSVs already uploaded to RAW_DATA_STAGE.
-- A failed rebuild must be rerun before dbt; this is not an atomic multi-table load.

USE ROLE DATA_OWNER;
USE DATABASE RAW;
USE SCHEMA PUBLIC;
USE WAREHOUSE TRANSFORM_WH;

-- ============================================
-- CREATE FILE FORMAT
-- ============================================
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null', '')
  EMPTY_FIELD_AS_NULL = TRUE;

-- ============================================
-- 1. CUSTOMER TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS RAW.PUBLIC.CUSTOMER (
  CUSTOMER_ID VARCHAR NOT NULL,
  FIRST_NAME VARCHAR,
  LAST_NAME VARCHAR,
  CUSTOMER_TYPE VARCHAR,
  TAX_ID VARCHAR,  -- SENSITIVE - will be masked
  DATE_OF_BIRTH DATE,  -- SENSITIVE - will be masked
  EMAIL VARCHAR,  -- SENSITIVE - will be masked
  PHONE VARCHAR,  -- SENSITIVE - will be masked
  ADDRESS VARCHAR,
  CREATED_AT TIMESTAMP_NTZ,
  _LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

TRUNCATE TABLE RAW.PUBLIC.CUSTOMER;
COPY INTO RAW.PUBLIC.CUSTOMER (
  CUSTOMER_ID, FIRST_NAME, LAST_NAME, CUSTOMER_TYPE, TAX_ID,
  DATE_OF_BIRTH, EMAIL, PHONE, ADDRESS, CREATED_AT
)
FROM @RAW_DATA_STAGE
FILES = ('customers.csv')
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT'
FORCE = TRUE;

-- ============================================
-- 2. ACCOUNT TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS RAW.PUBLIC.ACCOUNT (
  ACCOUNT_ID VARCHAR NOT NULL,
  CUSTOMER_ID VARCHAR NOT NULL,
  ACCOUNT_TYPE VARCHAR,
  ACCOUNT_NUMBER VARCHAR,  -- SENSITIVE - custom classifier
  BRANCH_CODE VARCHAR,
  BALANCE DECIMAL(15,2),
  STATUS VARCHAR,
  OPENED_DATE DATE,
  CREATED_AT TIMESTAMP_NTZ,
  _LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

TRUNCATE TABLE RAW.PUBLIC.ACCOUNT;
COPY INTO RAW.PUBLIC.ACCOUNT (
  ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, ACCOUNT_NUMBER, BRANCH_CODE,
  BALANCE, STATUS, OPENED_DATE, CREATED_AT
)
FROM @RAW_DATA_STAGE
FILES = ('accounts.csv')
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT'
FORCE = TRUE;

-- ============================================
-- 3. TRANSACTION TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS RAW.PUBLIC.TRANSACTION (
  TRANSACTION_ID VARCHAR NOT NULL,
  ACCOUNT_ID VARCHAR NOT NULL,
  TRANSACTION_TYPE VARCHAR,  -- DEBIT or CREDIT; source domain enforced by dbt tests
  AMOUNT DECIMAL(12,2),
  BUSINESS_DATE DATE,
  MEMO VARCHAR,  -- SENSITIVE: May contain PII in free text
  CREATED_AT TIMESTAMP_NTZ,
  _LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

TRUNCATE TABLE RAW.PUBLIC.TRANSACTION;
COPY INTO RAW.PUBLIC.TRANSACTION (
  TRANSACTION_ID, ACCOUNT_ID, TRANSACTION_TYPE, AMOUNT,
  BUSINESS_DATE, MEMO, CREATED_AT
)
FROM @RAW_DATA_STAGE
FILES = ('transactions.csv')
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT'
FORCE = TRUE;

-- ============================================
-- 4. LOAN TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS RAW.PUBLIC.LOAN (
  LOAN_ID VARCHAR NOT NULL,
  CUSTOMER_ID VARCHAR NOT NULL,
  ACCOUNT_ID VARCHAR,
  LOAN_TYPE VARCHAR,
  PRINCIPAL DECIMAL(15,2),
  INTEREST_RATE DECIMAL(5,2),
  CREDIT_GRADE VARCHAR,
  COLLATERAL_VALUE DECIMAL(15,2),
  LOAN_MEMO VARCHAR,  -- SENSITIVE: May contain hidden card PANs
  STATUS VARCHAR,
  ORIGINATION_DATE DATE,
  _LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

TRUNCATE TABLE RAW.PUBLIC.LOAN;
COPY INTO RAW.PUBLIC.LOAN (
  LOAN_ID, CUSTOMER_ID, ACCOUNT_ID, LOAN_TYPE, PRINCIPAL,
  INTEREST_RATE, CREDIT_GRADE, COLLATERAL_VALUE, LOAN_MEMO, STATUS,
  ORIGINATION_DATE
)
FROM @RAW_DATA_STAGE
FILES = ('loans.csv')
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT'
FORCE = TRUE;

-- ============================================
-- 5. GL_CONTROL TABLE (Reconciliation)
-- ============================================
CREATE TABLE IF NOT EXISTS RAW.PUBLIC.GL_CONTROL (
  GL_CODE VARCHAR NOT NULL,
  ACCOUNT_TYPE VARCHAR,
  CONTROL_TOTAL DECIMAL(15,2),
  RECORD_COUNT INTEGER,
  AS_OF_DATE DATE,
  _LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

TRUNCATE TABLE RAW.PUBLIC.GL_CONTROL;
COPY INTO RAW.PUBLIC.GL_CONTROL (
  GL_CODE, ACCOUNT_TYPE, CONTROL_TOTAL, RECORD_COUNT, AS_OF_DATE
)
FROM @RAW_DATA_STAGE
FILES = ('gl_control.csv')
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT'
FORCE = TRUE;

-- ============================================
-- REFERENCE TABLES
-- ============================================
CREATE TABLE IF NOT EXISTS RAW.PUBLIC.BRANCH (
  BRANCH_CODE VARCHAR NOT NULL,
  BRANCH_NAME VARCHAR,
  BRANCH_MANAGER VARCHAR,
  REGION VARCHAR
);

TRUNCATE TABLE RAW.PUBLIC.BRANCH;
COPY INTO RAW.PUBLIC.BRANCH (
  BRANCH_CODE, BRANCH_NAME, BRANCH_MANAGER, REGION
)
FROM @RAW_DATA_STAGE
FILES = ('branches.csv')
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT'
FORCE = TRUE;

CREATE TABLE IF NOT EXISTS RAW.PUBLIC.PRODUCT (
  PRODUCT_CODE VARCHAR NOT NULL,
  PRODUCT_NAME VARCHAR,
  ACCOUNT_TYPE VARCHAR,
  TIER VARCHAR
);

TRUNCATE TABLE RAW.PUBLIC.PRODUCT;
COPY INTO RAW.PUBLIC.PRODUCT (
  PRODUCT_CODE, PRODUCT_NAME, ACCOUNT_TYPE, TIER
)
FROM @RAW_DATA_STAGE
FILES = ('products.csv')
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT'
FORCE = TRUE;

-- ============================================
-- VALIDATION QUERIES
-- ============================================
SELECT '✓ CUSTOMER table loaded' AS status;
SELECT COUNT(*) as customer_count FROM RAW.PUBLIC.CUSTOMER;

SELECT '✓ ACCOUNT table loaded' AS status;
SELECT COUNT(*) as account_count FROM RAW.PUBLIC.ACCOUNT;

SELECT '✓ TRANSACTION table loaded' AS status;
SELECT COUNT(*) as transaction_count FROM RAW.PUBLIC.TRANSACTION;

SELECT '✓ LOAN table loaded' AS status;
SELECT COUNT(*) as loan_count FROM RAW.PUBLIC.LOAN;

SELECT '✓ GL_CONTROL table loaded' AS status;
SELECT * FROM RAW.PUBLIC.GL_CONTROL;
